### ISSUE TITLE
Barbarians running in circles and guards wont target other players

### ISSUE THREAD

**Issue by itstoasttime** [P3pp3rF1y/AncientWarfare2#1028]
Hey there,

when I raid a small city the barbarians just run in circles, the archers works fine, but the barbarians run in circles without going after you, and will only hit you if you get into a one block radius of them. When I raid the city, it causes major lag to the server as well.

I have a question also about how do I set the soldiers I create to target other players. We are in survival and cheats are disabled. Would I have to install a permissions mod to modify permissions for this to work or can I install a factions-like mod and the teams created in one mod affect the npcs in this mod?

One other thing is when I look at the logs, I occasionally see an error pop up relating to this mod, not sure what it does or if it affects anything.

I'm using minecraft version 1.7.10, any fix and help would be much appreciated thanks!

Minecraft version: 1.7.10

The error log for the third issue is as follows:
` [Server thread/ERROR] [FML]: A TileEntity type net.shadowmage.ancientwarfare.core.tile.TileResearchStation has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23) ~[dx.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105) ~[dh.class:?]
        at net.shadowmage.ancientwarfare.core.tile.TileOwned.func_145841_b(TileOwned.java:70) ~[TileOwned.class:?]
        at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_145841_b(TileResearchStation.java:168) ~[TileResearchStation.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:25:11] [Server thread/ERROR] [FML]: A TileEntity type net.shadowmage.ancientwarfare.core.tile.TileResearchStation has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23) ~[dx.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105) ~[dh.class:?]
        at net.shadowmage.ancientwarfare.core.tile.TileOwned.func_145841_b(TileOwned.java:70) ~[TileOwned.class:?]
        at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_145841_b(TileResearchStation.java:168) ~[TileResearchStation.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

**Comment by WinDanesz** [comment]
Hey,
We're not prividing any support for 1.7.10 anymore, please update to the latest version for fixes (1.12.2)

**Comment by P3pp3rF1y** [comment]
Closing as this is 1.7.10 thing
