### ISSUE TITLE
game is crashing

### ISSUE THREAD

**Issue by Spyridon-X** [P3pp3rF1y/AncientWarfare2#1154]
Whenever I try to open Minecraft, it always crashes. Crash report is below.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Xaeros_Minimap_20.11.0_Forge_1.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/25/20 7:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare NPCs (ancientwarfarenpc)
Caused by: net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:95)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkinPackImage(NpcClientProxy.java:128)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinImage(NpcSkinManager.java:113)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.lambda$loadSkinsFromSource$3(NpcSkinManager.java:77)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager$$Lambda$2153/2105373934.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:61)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinsFromSource(NpcSkinManager.java:56)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkins(NpcSkinManager.java:47)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkins(NpcClientProxy.java:119)
	at net.shadowmage.ancientwarfare.npc.AncientWarfareNPC.postInit(AncientWarfareNPC.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.BufferedImage.getRGB(BufferedImage.java:961)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:248)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110987_a(TextureUtil.java:48)
	at net.shadowmage.ancientwarfare.core.util.TextureImageBased.func_110551_a(TextureImageBased.java:21)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkinPackImage(NpcClientProxy.java:128)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinImage(NpcSkinManager.java:113)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.lambda$loadSkinsFromSource$3(NpcSkinManager.java:77)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager$$Lambda$2153/2105373934.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:61)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinsFromSource(NpcSkinManager.java:56)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkins(NpcSkinManager.java:47)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkins(NpcClientProxy.java:119)
	at net.shadowmage.ancientwarfare.npc.AncientWarfareNPC.postInit(AncientWarfareNPC.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 52093232 bytes (49 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version             | Source                                           | Signature                                |
	|:----- |:------------------------ |:------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJ | minecraft                | 1.12.2              | minecraft.jar                                    | None                                     |
	| LCHIJ | mcp                      | 9.42                | minecraft.jar                                    | None                                     |
	| LCHIJ | FML                      | 8.0.99.99           | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                    | 14.23.5.2854        | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | xaerominimap_core        | 1.12.2-1.0          | minecraft.jar                                    | None                                     |
	| LCHIJ | bspkrscore               | 8.0.0               | [1.12.2]bspkrscore-universal-8.0.1.jar           | None                                     |
	| LCHIJ | damageindicatorsmod      | 1.0                 | [1.12.2]DamageIndicatorsMod-3.5.1.jar            | None                                     |
	| LCHIJ | treecapitator            | 1.43.0              | [1.12]TreeCapitator-client-1.43.0.jar            | None                                     |
	| LCHIJ | aether_legacy            | 1.4.4               | aether_legacy-1.12.2-v1.4.4.jar                  | None                                     |
	| LCHIJ | codechickenlib           | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | ancientwarfare           | 1.12.2-2.7.0.772    | ancientwarfare-1.12.2-2.7.0.772.jar              | None                                     |
	| LCHIJ | ancientwarfarestructure  | 1.12.2-2.7.0.772    | ancientwarfare-1.12.2-2.7.0.772.jar              | None                                     |
	| LCHIJ | ancientwarfarevehicle    | 1.12.2-2.7.0.772    | ancientwarfare-1.12.2-2.7.0.772.jar              | None                                     |
	| LCHIE | ancientwarfarenpc        | 1.12.2-2.7.0.772    | ancientwarfare-1.12.2-2.7.0.772.jar              | None                                     |
	| LCHI  | ancientwarfareautomation | 1.12.2-2.7.0.772    | ancientwarfare-1.12.2-2.7.0.772.jar              | None                                     |
	| LCHI  | aoa3                     | 3.2.7               | AoA3-3.2.7.jar                                   | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHI  | backpack                 | 3.0.2               | backpack-3.0.2-1.12.2.jar                        | None                                     |
	| LCHI  | biomesoplenty            | 7.0.1.2439          | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar    | None                                     |
	| LCHI  | cfm                      | 6.3.0               | cfm-6.3.0-mc1.12.2.jar                           | None                                     |
	| LCHI  | ctm                      | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCHI  | customspawner            | 3.11.4              | CustomMobSpawner-3.11.5.jar                      | None                                     |
	| LCHI  | mocreatures              | 12.0.5              | DrZharks MoCreatures Mod-12.0.5.jar              | None                                     |
	| LCHI  | golems                   | 7.1.9               | ExtraGolems-1.12-7.1.9.jar                       | None                                     |
	| LCHI  | futureminecraf           | 1.2.2               | FutureVersionsV1.2.2.jar                         | None                                     |
	| LCHI  | ichunutil                | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | hats                     | 7.1.1               | Hats-1.12.2-7.1.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | inventorypets            | 2.0.5               | inventorypets-1.12-2.0.5.jar                     | None                                     |
	| LCHI  | jei                      | 4.15.0.293          | jei_1.12.2-4.15.0.293.jar                        | None                                     |
	| LCHI  | lycanitesmobs            | 2.0.7.2 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.7.2.jar                 | None                                     |
	| LCHI  | mantle                   | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHI  | mca                      | 6.1.0               | MCA-1.12.2-6.1.0-universal.jar                   | None                                     |
	| LCHI  | morph                    | 7.2.0               | Morph-1.12.2-7.2.0.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | llibrary                 | 1.7.19              | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHI  | mowziesmobs              | 1.5.4               | mowziesmobs-1.5.4.jar                            | None                                     |
	| LCHI  | additionalstructures     | 2.3.1               | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LCHI  | roguelike                | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCHI  | ruins                    | 17.1                | Ruins-1.12.2.jar                                 | None                                     |
	| LCHI  | twilightforest           | 3.10.1013           | twilightforest-1.12.2-3.10.1013-universal.jar    | None                                     |
	| LCHI  | xaerominimap             | 20.11.0             | Xaeros_Minimap_20.11.0_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Xaeros_Minimap_20.11.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer

**Comment by P3pp3rF1y** [comment]
I am pretty sure this is because you're running out of memory there (because you have 50 MB out of 2 GB remaining when this happens and there still plenty of stuff that needs to load). 2 GB of memory is way lower than what you need to run forge with additional mods. for forge + AW alone you probably need 4 GB as a minimum, when you add all those other mods you have there I would think it's more like 6GB
