### ISSUE TITLE
When I eat bread the game crashes

### ISSUE THREAD

**Issue by BIkBoi575** [P3pp3rF1y/AncientWarfare2#1193]
**The Issue tracker is mainly used for reporting bugs.**

New features, general discussion and suggestions should happen in our [Discord server](https://discord.gg/jNhkDfU). You'll also get your answers faster and can discuss with the dev team there.

Please use our [Discord server](https://discord.gg/jNhkDfU) for suggestions, we have a *#suggestions* channel for this purpose. We also have a list of all the existing suggestions [here](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List).

**The 1.7.10. version of the mod is not supported anymore, 1.12.2 is the actively developed version. Issues for the 1.7.10 version are automatically closed.**

Consult our other resources for more information about the mod: Treatise on principles of Ruling (Ingame Manual book), [Online Wiki](https://github.com/P3pp3rF1y/AncientWarfare2/wiki), [FAQ](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions), [Discord FAQ](https://discordapp.com/channels/440863937777369088/501101121775992859/673303026911412228), [Announcements](https://discordapp.com/channels/440863937777369088/576129126381912064/576129530075283486)

## Context Environment
Minecraft version:1.12.2

Ancient Warfare 2 version:2.7.0.772

Minecraft Forge version:14.23.5.2854

Link to your crash log (if the game crashes): 
Time: 8/21/20 6:13 PM
Description: Unexpected error

java.lang.AbstractMethodError: Method net/shadowmage/ancientwarfare/npc/entity/faction/NpcFactionArcherElite.func_184724_a(Z)V is abstract
	at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFactionArcherElite.func_184724_a(NpcFactionArcherElite.java)
	at me.ichun.mods.morph.client.morph.MorphInfoClient.syncEntityWithPlayer(MorphInfoClient.java:300)
	at me.ichun.mods.morph.common.morph.MorphInfo.tick(MorphInfo.java:115)
	at me.ichun.mods.morph.client.morph.MorphInfoClient.tick(MorphInfoClient.java:151)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:836)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2975_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFactionArcherElite.func_184724_a(NpcFactionArcherElite.java)
	at me.ichun.mods.morph.client.morph.MorphInfoClient.syncEntityWithPlayer(MorphInfoClient.java:300)
	at me.ichun.mods.morph.common.morph.MorphInfo.tick(MorphInfo.java:115)
	at me.ichun.mods.morph.client.morph.MorphInfoClient.tick(MorphInfoClient.java:151)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:836)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2975_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['BikBoi757'/673, l='MpServer', x=-347.66, y=162.00, z=134.99]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-48,70,-64), Chunk: (at 0,4,0 in -3,-4; contains blocks -48,0,-64 to -33,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 680898 game time, 9786 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 121 total; [EntityCreeper['Father Kenfor the §kAlien§r'/1026, l='MpServer', x=-394.12, y=10.19, z=169.88], EntityBat['Bat'/1027, l='MpServer', x=-375.02, y=49.10, z=145.92], EntitySpider['Skelaldy'/1028, l='MpServer', x=-360.96, y=45.00, z=128.70], EntityZombie['Zombie'/2308, l='MpServer', x=-322.50, y=112.00, z=78.50], EntityCreeper['Creeper'/1029, l='MpServer', x=-359.50, y=44.00, z=128.50], EntitySkeleton['Skeleton'/2309, l='MpServer', x=-321.50, y=112.00, z=81.50], EntityBat['Bat'/1030, l='MpServer', x=-362.35, y=41.36, z=149.07], EntityZombie['Zombie'/2310, l='MpServer', x=-325.50, y=112.00, z=73.50], EntityItem['item.item.tconstruct.edible.slimeball_blue'/1031, l='MpServer', x=-363.31, y=85.00, z=129.21], EntityZombie['Zombie'/2311, l='MpServer', x=-324.62, y=112.00, z=70.78], EntitySkeleton['Skeleton'/2317, l='MpServer', x=-329.50, y=52.00, z=150.50], EntityBat['Bat'/787, l='MpServer', x=-379.48, y=51.10, z=137.76], EntityCreeper['Creeper'/788, l='MpServer', x=-367.50, y=81.00, z=106.50], EntityRabbit['Rabbit'/1044, l='MpServer', x=-380.52, y=67.00, z=205.51], EntitySheep['Sheep'/789, l='MpServer', x=-308.53, y=101.00, z=61.27], EntityEnderman['Enderman'/1046, l='MpServer', x=-293.50, y=56.00, z=118.50], EntityItem['item.item.egg'/790, l='MpServer', x=-406.45, y=70.00, z=160.52], EntitySkeleton['Skeleton'/1047, l='MpServer', x=-293.77, y=55.00, z=114.50], EntityRabbit['Rabbit'/791, l='MpServer', x=-388.41, y=62.59, z=155.80], EntitySkeleton['Skeleton'/1048, l='MpServer', x=-298.50, y=56.00, z=119.50], EntitySkeleton['Skeleton'/793, l='MpServer', x=-390.50, y=50.00, z=120.50], EntitySkeleton['Skeleton'/1050, l='MpServer', x=-329.77, y=65.00, z=115.47], EntityBat['Bat'/794, l='MpServer', x=-380.56, y=52.32, z=114.48], EntityBlueSlime['Blue Slime'/1051, l='MpServer', x=-328.05, y=72.00, z=124.28], EntityBlueSlime['Blue Slime'/1052, l='MpServer', x=-341.14, y=76.00, z=118.59], EntitySpider['Spider'/796, l='MpServer', x=-376.50, y=50.00, z=99.50], EntityBat['Bat'/797, l='MpServer', x=-375.74, y=53.10, z=107.58], EntityBlueSlime['Blue Slime'/1054, l='MpServer', x=-334.20, y=72.00, z=126.74], EntityWitch['Witch'/798, l='MpServer', x=-377.50, y=51.00, z=110.50], EntityWorm['Worm'/801, l='MpServer', x=-349.50, y=123.50, z=79.50], EntityHorse['Horse'/1057, l='MpServer', x=-274.12, y=68.00, z=68.57], EntityHorse['Horse'/1058, l='MpServer', x=-273.13, y=68.00, z=64.87], EntityWorm['Worm'/802, l='MpServer', x=-349.50, y=123.50, z=71.50], EntityWorm['Worm'/803, l='MpServer', x=-349.50, y=123.50, z=74.50], EntityWorm['Worm'/805, l='MpServer', x=-343.50, y=123.50, z=71.50], EntityWorm['Worm'/806, l='MpServer', x=-343.50, y=123.50, z=74.50], EntityWorm['Worm'/807, l='MpServer', x=-343.50, y=123.50, z=79.50], EntityWorm['Worm'/808, l='MpServer', x=-340.50, y=123.50, z=79.50], EntityWorm['Worm'/809, l='MpServer', x=-340.50, y=123.50, z=73.50], EntityWorm['Worm'/810, l='MpServer', x=-340.50, y=123.50, z=71.50], EntityWorm['Worm'/811, l='MpServer', x=-340.50, y=123.50, z=76.50], EntityWorm['Worm'/812, l='MpServer', x=-346.50, y=123.50, z=79.50], EntityWorm['Worm'/813, l='MpServer', x=-346.50, y=123.50, z=76.50], EntityWorm['Worm'/814, l='MpServer', x=-346.50, y=123.50, z=73.50], EntityWorm['Worm'/815, l='MpServer', x=-349.50, y=123.50, z=77.50], EntityWorm['Worm'/816, l='MpServer', x=-343.50, y=123.50, z=77.50], EntitySheep['Sheep'/820, l='MpServer', x=-317.50, y=124.00, z=65.21], EntityBat['Bat'/1847, l='MpServer', x=-376.69, y=47.12, z=169.91], EntityBat['Bat'/1850, l='MpServer', x=-352.17, y=45.03, z=181.47], EntitySkeleton['Susan'/1086, l='MpServer', x=-365.23, y=30.00, z=213.49], EntityNightmare['Nightmare'/1087, l='MpServer', x=-315.02, y=62.62, z=171.30], EntityChicken['Chicken'/831, l='MpServer', x=-403.05, y=69.00, z=159.40], EntitySquid['Squid'/1088, l='MpServer', x=-303.98, y=62.19, z=167.07], EntitySquid['Squid'/1090, l='MpServer', x=-289.03, y=61.00, z=154.58], EntitySkeleton['Skeleton'/2372, l='MpServer', x=-352.50, y=40.00, z=156.50], EntitySheep['Sheep'/1093, l='MpServer', x=-271.27, y=73.00, z=127.50], EntitySkeleton['Skeleton'/2373, l='MpServer', x=-354.50, y=40.00, z=159.50], EntityZombie['Zombie'/2375, l='MpServer', x=-354.50, y=40.00, z=152.50], EntityPig['Pig'/1096, l='MpServer', x=-267.26, y=67.00, z=80.80], EntityBat['Bat'/1868, l='MpServer', x=-349.87, y=49.60, z=116.07], EntitySkeleton['Skeleton'/1107, l='MpServer', x=-286.50, y=56.00, z=116.50], EntitySheep['Sheep'/1108, l='MpServer', x=-281.50, y=74.00, z=114.73], EntitySheep['Sheep'/1109, l='MpServer', x=-274.27, y=74.00, z=124.80], EntitySheep['Sheep'/1110, l='MpServer', x=-282.77, y=75.00, z=122.83], EntityBat['Bat'/1880, l='MpServer', x=-381.96, y=52.02, z=113.49], EntitySquid['Squid'/1113, l='MpServer', x=-290.40, y=60.90, z=168.32], EntityBat['Bat'/1881, l='MpServer', x=-371.81, y=52.08, z=110.17], EntitySquid['Squid'/1114, l='MpServer', x=-286.60, y=62.00, z=150.40], EntityBat['Bat'/1883, l='MpServer', x=-375.81, y=50.08, z=106.35], EntitySquid['Squid'/1115, l='MpServer', x=-285.65, y=62.29, z=157.23], EntityBat['Bat'/1884, l='MpServer', x=-367.21, y=46.31, z=127.61], GCEntityClientPlayerMP['BikBoi757'/673, l='MpServer', x=-347.66, y=162.00, z=134.99], EntityLatchedRenderer['unknown'/1119, l='MpServer', x=8.50, y=65.00, z=8.50], EntityZombie['Zombie'/2463, l='MpServer', x=-346.50, y=101.00, z=57.50], EntityCreeper['Creeper'/2469, l='MpServer', x=-407.50, y=57.00, z=114.50], EntitySkeleton['Skeleton'/678, l='MpServer', x=-322.78, y=111.00, z=64.68], EntityCreeper['Creeper'/2470, l='MpServer', x=-408.50, y=57.00, z=115.50], EntityCreeper['Creeper'/679, l='MpServer', x=-340.22, y=111.00, z=82.40], EntityCreeper['Creeper'/680, l='MpServer', x=-321.52, y=114.00, z=84.16], EntitySkeleton['Skeleton'/681, l='MpServer', x=-327.66, y=112.00, z=70.51], EntityCreeper['Creeper'/682, l='MpServer', x=-326.86, y=112.00, z=74.64], EntitySpider['Spider'/1967, l='MpServer', x=-393.50, y=62.00, z=80.50], EntitySpider['Spider'/1974, l='MpServer', x=-357.50, y=84.00, z=99.50], EntityEnderman['Enderman'/1976, l='MpServer', x=-406.50, y=55.00, z=119.50], EntityZombieVillager['Zombie Villager'/1729, l='MpServer', x=-387.19, y=50.00, z=125.50], EntityCreeper['Creeper'/2241, l='MpServer', x=-358.50, y=83.00, z=106.50], EntityZombie['Zombie'/1732, l='MpServer', x=-375.81, y=79.00, z=98.49], EntityCreeper['Creeper'/1739, l='MpServer', x=-388.50, y=64.00, z=85.50], EntityBat['Bat'/973, l='MpServer', x=-333.59, y=43.91, z=129.21], EntityItem['item.item.tconstruct.edible.slimeball_blue'/974, l='MpServer', x=-343.88, y=153.63, z=127.73], EntityPig['Pig'/975, l='MpServer', x=-326.75, y=98.00, z=108.57], EntityHorse['Horse'/978, l='MpServer', x=-283.94, y=68.00, z=61.86], EntitySpider['Olivia the Dirt Digger'/728, l='MpServer', x=-424.70, y=13.82, z=91.70], EntityWroughtnaut['Ferrous Wroughtnaut'/734, l='MpServer', x=-402.50, y=3.00, z=112.50], EntityCreeper['Creeper'/735, l='MpServer', x=-401.53, y=54.00, z=117.82], EntitySpider['Spider'/736, l='MpServer', x=-405.50, y=54.00, z=126.50], EntityZombie['Zombie'/737, l='MpServer', x=-409.50, y=57.00, z=116.50], EntitySkeleton['Skeleton'/738, l='MpServer', x=-410.50, y=57.00, z=117.50], EntitySkeleton['Etteman'/740, l='MpServer', x=-394.01, y=9.01, z=101.30], EntityChicken['Chicken'/741, l='MpServer', x=-383.00, y=93.00, z=90.51], EntityChicken['Chicken'/742, l='MpServer', x=-374.20, y=96.00, z=95.80], EntityItem['item.item.egg'/743, l='MpServer', x=-376.13, y=97.00, z=92.25], EntitySkeleton['Skeleton'/747, l='MpServer', x=-348.53, y=102.00, z=59.90], EntityRabbit['Rabbit'/1004, l='MpServer', x=-378.29, y=69.00, z=164.52], EntityCreeper['Creeper'/1005, l='MpServer', x=-359.50, y=41.00, z=148.50], EntityZombie['Zombie'/1006, l='MpServer', x=-359.50, y=41.00, z=150.50], EntitySkeleton['Skeleton'/2542, l='MpServer', x=-346.30, y=46.00, z=117.51], EntityBlueSlime['Blue Slime'/1007, l='MpServer', x=-339.41, y=154.00, z=124.51], EntitySkeleton['Skeleton'/2543, l='MpServer', x=-346.50, y=44.00, z=126.50], EntityBat['Bat'/1008, l='MpServer', x=-374.08, y=45.08, z=138.04], EntityCreeper['Creeper'/1009, l='MpServer', x=-325.47, y=113.00, z=85.37], EntitySkeleton['Skeleton'/1010, l='MpServer', x=-321.48, y=114.00, z=85.21], EntityCreeper['Creeper'/1011, l='MpServer', x=-329.18, y=113.00, z=78.57], EntitySheep['Sheep'/1012, l='MpServer', x=-306.27, y=92.00, z=71.49], EntityCow['Cow'/1013, l='MpServer', x=-288.51, y=68.00, z=63.66], EntityBat['Bat'/1785, l='MpServer', x=-351.75, y=48.00, z=115.44], EntityPig['Pig'/763, l='MpServer', x=-402.71, y=91.00, z=103.49], EntityChicken['Chicken'/764, l='MpServer', x=-393.12, y=89.00, z=97.38], EntityItem['item.item.egg'/765, l='MpServer', x=-392.71, y=89.00, z=94.76], EntitySheep['Sheep'/766, l='MpServer', x=-378.55, y=100.00, z=63.41], EntitySheep['Sheep'/767, l='MpServer', x=-363.82, y=104.00, z=63.49]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/1119, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

If you are using a modpack, link to the pack: Direwolf 20, Crackpack 3, FTB Continuum 

## Expected Behavior
It shouldn't crash

## Current Behavior
The game crashes
## Steps to Reproduce
1.Load Game
2.Eat Bread
3.Game Crash
4.

## Possible Solution
Remove Ancient Warfare 2 or remove Morph Mod?

**Comment by ThatPolishKid99** [comment]
This seems to be a crash caused by the Morph mod, as reported by one of the users on our Discord, which you should join to avoid cluttering our issue tracker. Please report this issue to the Morph mod.
