### ISSUE TITLE
[Crash] [1.12.2] Server crashes when generating

### ISSUE THREAD

**Issue by NikeSchuh** [P3pp3rF1y/AncientWarfare2#1235]
Consult our other resources for more information about the mod: Treatise on principles of Ruling (Ingame Manual book), [Online Wiki](https://github.com/P3pp3rF1y/AncientWarfare2/wiki), [FAQ](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions), [Discord FAQ](https://discordapp.com/channels/440863937777369088/501101121775992859/673303026911412228), [Announcements](https://discordapp.com/channels/440863937777369088/576129126381912064/576129530075283486)

## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 1.12.2-2.7.0.1032

Minecraft Forge version: 14.23.5.2854

Link to your crash log (if the game crashes):
[00:00:41] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@215860b:
java.lang.NullPointerException: null
        at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.lambda$selectTemplateForGeneration$3(WorldGenStructureManager.java:137) ~[WorldGenStructureManager.class:?]
        at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_281]
        at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.selectTemplateForGeneration(WorldGenStructureManager.java:137) ~[WorldGenStructureManager.class:?]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.lambda$generateAt$1(WorldStructureGenerator.java:77) ~[WorldStructureGenerator.class:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.generateAt(WorldStructureGenerator.java:74) ~[WorldStructureGenerator.class:?]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.genChunks(WorldGenTickHandler.java:79) ~[WorldGenTickHandler.class:?]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:56) ~[WorldGenTickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_584_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[00:00:41] [Server thread/ERROR] [FML]: Index: 10 Listeners:
[00:00:41] [Server thread/ERROR] [FML]: 0: NORMAL
[00:00:41] [Server thread/ERROR] [FML]: 1: ASM: class crazypants.enderio.base.teleport.ChunkTicket onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 2: ASM: class crazypants.enderio.base.item.spawner.BrokenSpawnerHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 3: ASM: class crazypants.enderio.base.handler.ServerTickHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 4: ASM: class crazypants.enderio.base.init.TickTimer onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 5: ASM: class crazypants.enderio.base.TileEntityEio onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 6: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesServerEventHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 7: ASM: class blusunrize.immersiveengineering.common.blocks.BlockIETileProvider onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 8: ASM: net.minecraftforge.common.ForgeInternalHandler@6a4bbfc3 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 9: ASM: com.shinoow.abyssalcraft.common.handlers.AbyssalCraftEventHooks@55fd51ee onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 10: ASM: net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler@57081322 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 11: ASM: class vazkii.patchouli.common.handler.AdvancementSyncHandler onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 12: ASM: codechicken.enderstorage.network.TankSynchroniser@2f5e5df5 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 13: ASM: INSTANCE onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 14: ASM: com.enderio.core.common.util.Scheduler@2195efbf onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 15: ASM: com.pg85.otg.forge.events.server.ServerTickHandler@298160f0 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 16: ASM: ru.socol.elderarsenal.ModListener@5baed64a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 17: ASM: li.cil.oc.common.EventHandler$@41edba2f onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)Ljava/lang/Object;
[00:00:41] [Server thread/ERROR] [FML]: 18: ASM: li.cil.oc.common.asm.SimpleComponentTickHandler@47199a1f onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 19: ASM: li.cil.oc.common.item.Tablet$@6dc29c57 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 20: ASM: openblocks.common.ServerTickHandler@69b38647 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 21: ASM: org.orecruncher.dsurround.server.services.ServiceManager@67b6a706 tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 22: ASM: net.shadowmage.ancientwarfare.core.command.CommandUtils$ChunkLoadCommand$PlayerMover@7ae714c serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 23: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[00:00:41] [Server thread/ERROR] [FML]: 24: LOWEST
[00:00:41] [Server thread/ERROR] [FML]: 25: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[00:00:41] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.lambda$selectTemplateForGeneration$3(WorldGenStructureManager.java:137) ~[WorldGenStructureManager.class:?]
        at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_281]
        at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.selectTemplateForGeneration(WorldGenStructureManager.java:137) ~[WorldGenStructureManager.class:?]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.lambda$generateAt$1(WorldStructureGenerator.java:77) ~[WorldStructureGenerator.class:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.generateAt(WorldStructureGenerator.java:74) ~[WorldStructureGenerator.class:?]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.genChunks(WorldGenTickHandler.java:79) ~[WorldGenTickHandler.class:?]
        at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:56) ~[WorldGenTickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_584_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[00:00:41] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\phili\Documents\Server\PVP - 1.12.2 - Saft\.\crash-reports\crash-2021-02-23_00.00.41-server.txt

If you are using a modpack, link to the pack: 
https://www.file-upload.net/download-14496015/ModsEntpackendundinmodsziehen.zip.html

## Expected Behavior
The server should just generate a structure instead of crashing

## Current Behavior
Crash

## Steps to Reproduce
1. Start the Server
2. Fly around
3.
4.

**Comment by ThatPolishKid99** [comment]
We need more information, because I am not going to download your modpack from that sketchy looking website where I can't even find the download button. Can you replicate this with just Ancient Warfare and CodeChickenLib? Which structures were you near when it crashed?

**Comment by mr-poyo** [comment]
I also experienced a similar crash with my own custom modpack. I suspect it's because of OTG which is listed on the main page as incompatible. I added it for testing and using CTRL+F on OP's log, i see that he also has OTG. 

Here's my crash report if I'm incorrect on the OTG incompatibility: https://pastebin.com/SuqZbpXJ

**Comment by SyndicMohawky** [comment]
This is why we stress that OTG is incompatible. Neither of these crashes are an AW issue when you are using a world gen mod we specifically tell you not to use. You need to dump OTG and use AW2 - or Use OTG and find a different structure mod than AW2. There is no way around this, its either / or.
