### ISSUE TITLE
it crashes game when loading the structures file

### ISSUE THREAD

**Issue by Elixient** [P3pp3rF1y/AncientWarfare2#1243]
## Context Environment
Minecraft version: 12.2.2

Ancient Warfare 2 version: 2.7.0.1032

Minecraft Forge version:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/2/21 10:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)
Caused by: java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseBlocks(TemplateParser.java:269)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayerRows(TemplateParser.java:246)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayer(TemplateParser.java:224)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayer(TemplateParser.java:220)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplateLines(TemplateParser.java:185)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplate(TemplateParser.java:35)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplate(TemplateLoader.java:128)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.lambda$loadTemplatesFromSource$2(TemplateLoader.java:100)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader$$Lambda$1690/1409661450.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:66)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:24)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplatesFromSource(TemplateLoader.java:85)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplates(TemplateLoader.java:67)
	at net.shadowmage.ancientwarfare.structure.AncientWarfareStructure.postInit(AncientWarfareStructure.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 302712600 bytes (288 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                        | Signature                                |
	|:----- |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJ | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJ | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                    | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | ivtoolkit                | 1.3.3-1.12        | minecraft.jar                                 | None                                     |
	| LCHIJ | aether_legacy            | 1.5.3.1           | aether-1.12.2-v1.5.3.1.jar                    | None                                     |
	| LCHIJ | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJ | jei                      | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCHIJ | ebwizardry               | 4.3.4             | ElectroblobsWizardry-4.3.4-MC1.12.2.jar       | None                                     |
	| LCHIJ | ancientspellcraft        | 1.1.2             | AncientSpellcraft-1.1.2.jar                   | None                                     |
	| LCHIJ | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | ancientwarfare           | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJ | ancientwarfareautomation | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJ | ancientwarfarenpc        | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIE | ancientwarfarestructure  | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHI  | ancientwarfarevehicle    | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHI  | arcane_essentials        | 1.0               | Arcane+Essentials-1.0.0-alpha-11.jar          | None                                     |
	| LCHI  | battletowers             | 1.6.5             | BattleTowers-1.12.2.jar                       | None                                     |
	| LCHI  | cyclicmagic              | 1.8.5             | Cyclic-1.12-1.8.5.jar                         | None                                     |
	| LCHI  | mocreatures              | 12.0.5            | DrZharks+MoCreatures+Mod-12.0.5.jar           | None                                     |
	| LCHI  | golems                   | 7.1.9             | ExtraGolems-1.12-7.1.9.jar                    | None                                     |
	| LCHI  | potioncore               | 1.9_for_1.12.2    | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
	| LCHI  | extra_spells             | 1.2.0             | ExtraSpells-1.12.2-1.2.0.jar                  | None                                     |
	| LCHI  | llibrary                 | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHI  | fossil                   | 8.0.5             | fossilsarcheology-8.0.5.jar                   | None                                     |
	| LCHI  | iceandfire               | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHI  | infernalmobs             | 1.7.6             | InfernalMobs-1.12.1.jar                       | None                                     |
	| LCHI  | lost_aether              | 1.0.2             | lost-aether-content-1.12.2-1.0.2.jar          | None                                     |
	| LCHI  | mowziesmobs              | 1.5.8             | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHI  | reccomplex               | 1.4.8.2           | RecurrentComplex-1.4.8.2.jar                  | None                                     |
	| LCHI  | roguelike                | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCHI  | spawntemple              | 2.1               | SpawnTemple-v.2.1-mc1.12.jar                  | None                                     |
	| LCHI  | twilightforest           | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHI  | tfspellpack              | 1.1.0             | TFSpellPack-1.1.0-MC1.12.2.jar                | None                                     |
	| LCHI  | travellersbackpack       | 1.0.27            | TravellersBackpack-1.12.2-1.0.27.jar          | None                                     |
	| LCHI  | wizardrygolems           | 1.0.1             | WizardryGolems-1.0.1.jar                      | None                                     |
	| LCHI  | zettaimagic              | 1.3.9             | ZettaiMagic+1.3.9.jar                         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher

## Current Behavior

it crashed when loading the game
## Steps to Reproduce
1.
2.
3.
4.

**Comment by SyndicMohawky** [comment]
You dont have enough ram assigned to minecraft for the number and kinds of mods you are running - go to our discord and look in faq for advice
