### ISSUE TITLE
can't start minecraft with this mod

### ISSUE THREAD

**Issue by NorazShaman** [P3pp3rF1y/AncientWarfare2#1286]
**The Issue tracker is mainly used for reporting bugs.**

New features, general discussion and suggestions should happen in our [Discord server](https://discord.gg/jNhkDfU). You'll also get your answers faster and can discuss with the dev team there.

Please use our [Discord server](https://discord.gg/jNhkDfU) for suggestions, we have a *#suggestions* channel for this purpose. We also have a list of all the existing suggestions [here](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List).

**The 1.7.10. version of the mod is not supported anymore, 1.12.2 is the actively developed version. Issues for the 1.7.10 version are automatically closed.**

Consult our other resources for more information about the mod: Treatise on principles of Ruling (Ingame Manual book), [Online Wiki](https://github.com/P3pp3rF1y/AncientWarfare2/wiki), [FAQ](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions), [Discord FAQ](https://discordapp.com/channels/440863937777369088/501101121775992859/673303026911412228), [Announcements](https://discordapp.com/channels/440863937777369088/576129126381912064/576129530075283486)

## Context Environment
Minecraft version:
1.12.2
Ancient Warfare 2 version:
2.7.0.1032
Minecraft Forge version:
14.23.5.2855
Link to your crash log (if the game crashes):
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/20/21 10:23 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.String.substring(String.java:1957)
	at net.minecraft.nbt.JsonToNBT.func_193614_i(SourceFile:148)
	at net.minecraft.nbt.JsonToNBT.func_193601_b(SourceFile:57)
	at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:183)
	at net.minecraft.nbt.JsonToNBT.func_193610_d(SourceFile:160)
	at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:190)
	at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:34)
	at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:29)
	at net.shadowmage.ancientwarfare.structure.template.StructurePluginManager.readTag(StructurePluginManager.java:227)
	at net.shadowmage.ancientwarfare.structure.template.StructurePluginManager.getRule(StructurePluginManager.java:197)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplateLines(TemplateParser.java:132)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplate(TemplateParser.java:35)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplate(TemplateLoader.java:128)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.lambda$loadTemplatesFromSource$2(TemplateLoader.java:100)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader$$Lambda$671/1217032123.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:66)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:24)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplatesFromSource(TemplateLoader.java:85)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplates(TemplateLoader.java:67)
	at net.shadowmage.ancientwarfare.structure.AncientWarfareStructure.postInit(AncientWarfareStructure.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 344275384 bytes (328 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                        | Signature                                |
	|:----- |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJ | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJ | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                    | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | codechickenlib           | 3.2.3.358         | codechickenlib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | ancientwarfare           | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJ | ancientwarfareautomation | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJ | ancientwarfarenpc        | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIE | ancientwarfarestructure  | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHI  | ancientwarfarevehicle    | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHI  | jei                      | 4.16.1.301        | jei_1.12.2_4.16.1.301.jar                     | None                                     |
	| LCHI  | nei                      | 2.4.3             | NotEnoughItems_1.12.2_2.4.3.245_universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | harvestcraft             | 1.12.2zb          | PamsHarvestCraft1.12.2ze.jar                  | None                                     |
	| LCHI  | srparasites              | 1.9.0             | SRParasites-1.12.2v1.9.0ALPHA14.jar           | None                                     |
	| LCHI  | toughasnails             | 3.1.0.140         | ToughAsNails_1.12.2_3.1.0.140_universal.jar   | None                                     |

	Loaded coremods (and transformers): 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 30
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 462.30
	OpenGlRenderer: GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
If you are using a modpack, link to the pack: 

## Expected Behavior
start minecraft

## Current Behavior
don't start minecraft

## Steps to Reproduce
1.
2.
3.
4.

**Comment by SyndicMohawky** [comment]
Assign more RAM 2gb is nowhere near enough for modded minecraft. 

Your forge is also the wrong version.

Your AW is not the latest version.

**Comment by NorazShaman** [comment]
> Assign more RAM 2gb is nowhere near enough for modded minecraft.
> wait, i have 16GB RAM on my computer, how can i use more?
> Your forge is also the wrong version.
> what's the correct version?
> Your AW is not the latest version.
>i will update

**Comment by SyndicMohawky** [comment]
These are not Github issues. Please join our Discord and check the FAQ channel for information and advice.

**Comment by NorazShaman** [comment]
> These are not Github issues. Please join our Discord and check the FAQ channel for information and advice.

ok, thanks!
