### ISSUE TITLE
singer player crash many times

### ISSUE THREAD

**Issue by gta5plyaer** [P3pp3rF1y/AncientWarfare2#1333]
## Context Environment
Minecraft version:
1.12.2
Ancient Warfare 2 version:
1.12.2--2.7.0.1038
Minecraft Forge version:
14.23.5.2855
Link to your crash log (if the game crashes):
crash-report 1:

---- Minecraft Crash Report ----
// Don't do that.

Time: 2021-08-25 16:41:23 GMT+08:00
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.lambda$selectTemplateForGeneration$3(WorldGenStructureManager.java:137)
    at java.util.Collection.removeIf(Unknown Source)
    at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.selectTemplateForGeneration(WorldGenStructureManager.java:137)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.lambda$generateAt$1(WorldStructureGenerator.java:77)
    at java.util.Optional.ifPresent(Unknown Source)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.generateAt(WorldStructureGenerator.java:74)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.genChunks(WorldGenTickHandler.java:79)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:56)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_647_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

crash report 2:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2021-08-25 16:41:29 GMT+08:00
Description: Batching chunks

java.lang.IllegalStateException: Not building!
    at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:745)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178584_a(RenderChunk.java:514)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:359)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
    at java.lang.Thread.run(Unknown Source)

crash report 3:
--- Minecraft Crash Report ----
// Shall we play a game?

Time: 2021-08-25 16:43:46 GMT+08:00
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.lambda$selectTemplateForGeneration$3(WorldGenStructureManager.java:137)
    at java.util.Collection.removeIf(Unknown Source)
    at net.shadowmage.ancientwarfare.structure.template.WorldGenStructureManager.selectTemplateForGeneration(WorldGenStructureManager.java:137)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.lambda$generateAt$1(WorldStructureGenerator.java:77)
    at java.util.Optional.ifPresent(Unknown Source)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.generateAt(WorldStructureGenerator.java:74)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.genChunks(WorldGenTickHandler.java:79)
    at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:56)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_647_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

## Current Behavior
when i walk while playing single mode,the game crashed
first tme i assume that it is my shadowpack's problem, but i close shadow mode , the problem still exist

**Comment by gta5plyaer** [comment]
[
[crash-2021-08-25_16.41.23-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7047682/crash-2021-08-25_16.41.23-server.txt)
](url)
[
[crash-2021-08-25_16.41.29-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7047685/crash-2021-08-25_16.41.29-client.txt)
](url)
[
[crash-2021-08-25_16.43.46-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7047687/crash-2021-08-25_16.43.46-server.txt)
](url)

**Comment by SyndicMohawky** [comment]
Wrong forge version. OTG incompatible mod. AW will not work on OTG terrain gen. No, before you ask, there is no way to make it work. Try RTG terrain gen instead.

**Comment by Ezoteric** [comment]
older versions of both aw2 and otg worked so there is one way of fixing it
also RTG isnt even in a release state so you are suggesting ppl use beta builds of mods ?

**Comment by SyndicMohawky** [comment]
OTG has NEVER worked with AW, and there is no way of fixing it.
And the RTG beta is perfectly usable.

**Comment by SyndicMohawky** [comment]
From our Discord FAQ:

**Is this mod compatible with OTG or Conquest Reforged?**

OTG, Climatic Biomes, ATG, TerraFirmacraft, Conquest Reforged and EarthMap are completely incompatible with AW - this has been said many times. You may see some structures spawning, but they will not be the correct ones, in the correct biomes, height and elevation will be wrong and they are frequently miss-spawned. Plus 75% of AW structures will not spawn anywhere in OTG or Conquest Reforged. 

And before you ask, there is nothing on our side we can, or will do to change it. The world gen systems these mods use are completely different to the one that AW relies on. RTG works fine, and AW structures spawn correctly using that mod. 

In addition to being incompatible with AW2, Conquest's worldgen for 1.12.2 is completely broken and unmodifiable except by using biometweaker, and it is now abandoned in 1.12.2 by its own developers.

Insisting that these mods and AW2 work together, just because you see a few structures spawning WILL get you kicked.

**Comment by Ezoteric** [comment]
The reason OTG IS compatible is because: 
A: If you just use OTG default world gen ALL biomes are vanilla and thus works for all your structures that use vanilla biomes.
B: Lookup all biomes that AW2 uses and rename the biomes from OTG to those and there is your fully working AW2.


OTG just needs some tweaking as it uses renametobiome system which means you can decide what name the biome will get ingame.
Example:
In the OTG biome file tropicaldesert you set the renametobiome to desert and that biome will be acting and be called desert ingame and it will spawn AW2 structures.

BUT as i mentioned before after the update that inculded your new structures OTG crashes on startup but its still working for older versions.

Just redirect ppl who nag about it to this post and they can figure it out themselves.

**Comment by SyndicMohawky** [comment]
Everything you just said means OTG is incompatible.

**Comment by Ezoteric** [comment]
Running OTG default or with vanilla vistas IS compatible out of the box.
