### ISSUE TITLE
The game crashed whilst initializing game Error: SplashProgress has detected a error loading Minecraft. Exit Code: -1

### ISSUE THREAD

**Issue by GhostlyVixo** [P3pp3rF1y/AncientWarfare2#1370]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.23.0_Forge_1.12 (1).jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/8/22 8:50 PM
Description: Initializing game

SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
net.minecraftforge.fml.client.SplashProgress$4: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:677)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:669)
	at net.minecraftforge.fml.client.FMLClientHandler.haltGame(FMLClientHandler.java:311)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:349)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:601)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:656)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.CopyOnWriteArrayList.iterator(CopyOnWriteArrayList.java:1076)
	at net.minecraftforge.fml.common.ProgressManager.barIterator(ProgressManager.java:92)
	at net.minecraftforge.fml.client.SplashProgress$2.run(SplashProgress.java:265)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:677)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:669)
	at net.minecraftforge.fml.client.FMLClientHandler.haltGame(FMLClientHandler.java:311)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:349)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 316177792 bytes (301 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                            | Signature                                |
	|:----- |:------------------------ |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJ | mcp                      | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJ | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                    | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | xaerominimap_core        | 1.12.2-1.0        | minecraft.jar                                     | None                                     |
	| LCHIJ | magistuarmory            | 1.0               | [1.12.2]-Epic-Knights-Armor-and-Weapons-4.13v.jar | None                                     |
	| LCHIJ | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar              | None                                     |
	| LCHIJ | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar              | None                                     |
	| LCHIJ | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar              | None                                     |
	| LCHIE | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar              | None                                     |
	| LCHI  | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar              | None                                     |
	| LCHI  | customnpcs               | 1.12              | CustomNPCs_1.12.2-(05Jul20).jar                   | None                                     |
	| LCHI  | enhancedfarming          | 1.1.3             | Enhanced-Farming-1.12.2-1.1.3 (1).jar             | None                                     |
	| LCHI  | jei                      | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                         | None                                     |
	| LCHI  | moreplayermodels         | 1.12.2            | MorePlayerModels_1.12.2-(05Dec19).jar             | None                                     |
	| LCHI  | xaerominimap             | 21.23.0           | Xaeros_Minimap_21.23.0_Forge_1.12 (1).jar         | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.23.0_Forge_1.12 (1).jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.09' Renderer: 'NVIDIA GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 497.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz

**Comment by SyndicMohawky** [comment]
"Memory: 316177792 bytes (301 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)"

You have nowhere near enough RAM assigned for any kind of modded minecraft - you need 6 GB max at least, and your minimum should be half that. This is not an AW2 issue, its a lack of basic resources issue.
