### ISSUE TITLE
Game Crash, need to identify the problem! Ancient Warefare 1.12.2

### ISSUE THREAD

**Issue by iggibeast** [P3pp3rF1y/AncientWarfare2#1389]
---- Minecraft Crash Report ----
// My bad.

Time: 3/31/22 11:53 PM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.BufferedImage.getRGB(BufferedImage.java:961)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:248)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1375)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1296)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.awt.image.BufferedImage.getRGB(BufferedImage.java:961)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:248)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/environment/sun.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1375)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1296)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['iggibeast'/267, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['iggibeast'/267, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 319486280 bytes (304 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version           | Source                                        | Signature                                |
	|:------ |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.100.9955' Renderer: 'Intel(R) Iris(R) Xe Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: Intel(R) Iris(R) Xe Graphics GL version 4.6.0 - Build 30.0.100.9955, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz

**Comment by SyndicMohawky** [comment]
NOT AN AW PROBLEM. YOU HAVE NOT ASSIGNED ENOUGH RAM TO PLAY MODDED MINECRAFT!
