### ISSUE TITLE
游戏进不去，哪里有问题

### ISSUE THREAD

**Issue by dongfengcai** [P3pp3rF1y/AncientWarfare2#1395]
**The Issue tracker is mainly used for reporting bugs.**

New features, general discussion and suggestions should happen in our [Discord server](https://discord.gg/jNhkDfU). You'll also get your answers faster and can discuss with the dev team there.

Please use our [Discord server](https://discord.gg/jNhkDfU) for suggestions, we have a *#suggestions* channel for this purpose. We also have a list of all the existing suggestions [here](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List).

**The 1.7.10. version of the mod is not supported anymore, 1.12.2 is the actively developed version. Issues for the 1.7.10 version are automatically closed.**

Consult our other resources for more information about the mod: Treatise on principles of Ruling (Ingame Manual book), [Online Wiki](https://github.com/P3pp3rF1y/AncientWarfare2/wiki), [FAQ](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions), [Discord FAQ](https://discordapp.com/channels/440863937777369088/501101121775992859/673303026911412228), [Announcements](https://discordapp.com/channels/440863937777369088/576129126381912064/576129530075283486)

## Context Environment
Minecraft version:

Ancient Warfare 2 version:

Minecraft Forge version:

Link to your crash log (if the game crashes):

If you are using a modpack, link to the pack: 

## Steps to Reproduce
1.
2.
3.
4.
[03:03:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[03:03:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[03:03:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[03:03:57] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[03:03:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows 10:amd64:10.0, installed at C:\ProgramData\Oracle\Java-PE\jre1.8\x64
[03:03:57] [main/INFO] [FML]: Searching D:\Game\.minecraft\versions\1.12.2-Forge_14.23.5.2860-OptiFine_G5\mods for mods
[03:03:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:03:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[03:03:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:03:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:03:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:03:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[03:04:00] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[03:04:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:04:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[03:04:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[03:04:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[03:04:01] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[03:04:02] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:55]: Completely ignored arguments: [480, PCL2, ]
[03:04:03] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: 冬封蔡
[03:04:08] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: 
[03:04:08] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: 
[03:04:08] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: 
[03:04:08] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: 
[03:04:08] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[03:04:09] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 80627048 bytes (76 MB) / 374341632 bytes (357 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 20.45.44 27.20.14544.6' Renderer: 'AMD Radeon(TM) Vega 3 Graphics'
[03:04:09] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[03:04:09] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[03:04:09] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[03:04:10] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[03:04:10] [Client thread/INFO] [FML]: Searching D:\Game\.minecraft\versions\1.12.2-Forge_14.23.5.2860-OptiFine_G5\mods for mods
[03:04:13] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 333579800 nanos
[03:04:13] [Client thread/INFO] [FML]: Forge Mod Loader has identified 9 mods to load
[03:04:13] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod ancientwarfare (Ancient Warfare Core) requires [codechickenlib@[3.2.3,)]
[03:04:13] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod ancientwarfare (Ancient Warfare Core) requires [codechickenlib@[3.2.3,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[03:04:13] [Client thread/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[03:04:13] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Ancient Warfare Automation, FMLFileResourcePack:Ancient Warfare Core, FMLFileResourcePack:Ancient Warfare NPCs, FMLFileResourcePack:Ancient Warfare Structures, FMLFileResourcePack:Ancient Warfare Vehicles
[03:04:13] [Client thread/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[03:04:16] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[03:04:16] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[03:04:16] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[03:04:17] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[03:04:18] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[03:04:18] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[03:04:19] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient]: Could not authorize you against Realms server: Invalid session id

**Comment by ThatPolishKid99** [comment]
Use CodeChickenLib for 1.12
