### ISSUE TITLE
 Problems occurred when idea started the project

### ISSUE THREAD

**Issue by MClaozi** [P3pp3rF1y/AncientWarfare2#1407]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/16/22 10:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Automation (ancientwarfareautomation)
Caused by: java.lang.ExceptionInInitializerError
	at net.shadowmage.ancientwarfare.automation.proxy.ClientProxyAutomation.preInit(ClientProxyAutomation.java:108)
	at net.shadowmage.ancientwarfare.automation.AncientWarfareAutomation.preInit(AncientWarfareAutomation.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.init(Minecraft.java:514)
	at net.minecraft.client.Minecraft.run(Minecraft.java:422)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
Caused by: java.lang.RuntimeException: failed to load model: ancientwarfare:models/block/automation/torque_transport.obj
	at codechicken.lib.render.OBJParser.parseModels(OBJParser.java:67)
	at net.shadowmage.ancientwarfare.core.render.BaseBakery.<init>(BaseBakery.java:47)
	at net.shadowmage.ancientwarfare.core.render.RotatableBlockRenderer.<init>(RotatableBlockRenderer.java:18)
	at net.shadowmage.ancientwarfare.automation.render.AnimatedBlockRenderer.<init>(AnimatedBlockRenderer.java:22)
	at net.shadowmage.ancientwarfare.automation.render.BaseTorqueRenderer.<init>(BaseTorqueRenderer.java:25)
	at net.shadowmage.ancientwarfare.automation.render.TorqueTieredRenderer.<init>(TorqueTieredRenderer.java:19)
	at net.shadowmage.ancientwarfare.automation.render.TorqueTransportSidedRenderer.<init>(TorqueTransportSidedRenderer.java:23)
	at net.shadowmage.ancientwarfare.automation.render.TorqueJunctionRenderer.<init>(TorqueJunctionRenderer.java:20)
	at net.shadowmage.ancientwarfare.automation.render.TorqueJunctionRenderer.<clinit>(TorqueJunctionRenderer.java:17)
	... 48 more
Caused by: java.io.FileNotFoundException: ancientwarfare:models/block/automation/torque_transport.obj
	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:69)
	at codechicken.lib.render.OBJParser.parseModels(OBJParser.java:64)
	... 56 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 500051496 bytes (476 MB) / 946339840 bytes (902 MB) up to 7598505984 bytes (7246 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2816 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version               | Source                                                                     | Signature |
	|:----- |:------------------------ |:--------------------- |:-------------------------------------------------------------------------- |:--------- |
	| LCH   | minecraft                | 1.12.2                | minecraft.jar                                                              | None      |
	| LCH   | mcp                      | 9.42                  | minecraft.jar                                                              | None      |
	| LCH   | FML                      | 8.0.99.99             | forgeSrc-1.12.2-14.23.5.2816-PROJECT(AncientWarfare-1.12.2-2.7.0.1038).jar | None      |
	| LCH   | forge                    | 14.23.5.2816          | forgeSrc-1.12.2-14.23.5.2816-PROJECT(AncientWarfare-1.12.2-2.7.0.1038).jar | None      |
	| LCH   | codechickenlib           | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358.jar                                        | None      |
	| LCH   | ancientwarfare           | 1.12.2-2.7.0.unstable | main                                                                       | None      |
	| LCH   | redstoneflux             | 2.0.2                 | RedstoneFlux-1.12-2.0.2.3.jar                                              | None      |
	| LCE   | ancientwarfareautomation | 1.12.2-2.7.0.unstable | main                                                                       | None      |
	| LC    | ancientwarfarenpc        | 1.12.2-2.7.0.unstable | main                                                                       | None      |
	| LC    | ancientwarfarestructure  | 1.12.2-2.7.0.unstable | main                                                                       | None      |
	| LC    | ancientwarfarevehicle    | 1.12.2-2.7.0.unstable | main                                                                       | None      |
	| LC    | ebwizardry               | 4.2.11                | electroblobswizardry-265642-2929294.jar                                    | None      |
	| LC    | infinitylib              | 1.12.2-1.12.0         | infinitylib-251396-2537265.jar                                             | None      |
	| LC    | agricraft                | 2.12.0-1.12.0-a6      | agricraft-225635-2609648.jar                                               | None      |
	| LC    | jei                      | 4.11.0.212            | jei_1.12.2-4.11.0.212.jar                                                  | None      |
	| LC    | ftblib                   | 5.4.4.5               | ftb-library-legacy-forge-237167-2832410.jar                                | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2'

**Comment by ThatPolishKid99** [comment]
Use the latest release on Curseforge. The version you have is not supported. Also update Forge
