### ISSUE TITLE
Crash after loading mods

### ISSUE THREAD

**Issue by DaBomb1945** [P3pp3rF1y/AncientWarfare2#1418]
The application does not even fully load before it crashes, here is the crash report

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/11/22 11:39 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseBlocks(TemplateParser.java:269)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayerRows(TemplateParser.java:246)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayer(TemplateParser.java:224)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayer(TemplateParser.java:220)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplateLines(TemplateParser.java:185)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplate(TemplateParser.java:35)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplate(TemplateLoader.java:128)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.lambda$loadTemplatesFromSource$2(TemplateLoader.java:100)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader$$Lambda$1856/911624816.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:66)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:24)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplatesFromSource(TemplateLoader.java:85)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplates(TemplateLoader.java:67)
	at net.shadowmage.ancientwarfare.structure.AncientWarfareStructure.postInit(AncientWarfareStructure.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 277598944 bytes (264 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                        | Signature                                |
	|:----- |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJ | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJ | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                    | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJ | buildcraftlib            | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJ | buildcraftcore           | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJ | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJ | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIE | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHI  | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHI  | bibliocraft              | 2.4.5             | BiblioCraft-Mod-1.12.2.jar                    | None                                     |
	| LCHI  | biomesoplenty            | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHI  | buildcraftbuilders       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | buildcrafttransport      | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | buildcraftsilicon        | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | ic2                      | 2.8.221-ex112     | industrialcraft-2-2.8.221-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | buildcraftcompat         | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | buildcraftenergy         | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | buildcraftfactory        | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | buildcraftrobotics       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHI  | energycontrol            | 1.12.2-0.1.14     | EnergyControl-1.12.2-0.1.14.jar               | None                                     |
	| LCHI  | jei                      | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCHI  | jeiintegration           | 1.6.0             | jeiintegration_1.12.2-1.6.0.jar               | None                                     |
	| LCHI  | journeymap               | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHI  | jeresources              | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCHI  | railcraft                | 12.0.0            | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHI  | wawla                    | 2.6.275           | Wawla-1.12.2-2.6.275.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | waystones                | 4.1.0             | Waystones_1.12.2-4.1.0.jar                    | None                                     |

	Loaded coremods (and transformers):

**Comment by SyndicMohawky** [comment]
You have nowhere near enough RAM allocated for modded minecraft =

"Memory: 277598944 bytes (264 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)"

You need 6gb minimum.
