### ISSUE TITLE
Crash trying to load Minecraft Ancient Warfare Mod:  LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/BlockEvent$BreakEvent

### ISSUE THREAD

**Issue by DarthColin62** [P3pp3rF1y/AncientWarfare2#204]
Trying to add Ancient Warfare Mod.  Have Forge.  Forge, MC, and AW all are version 1.6.4. Dragged zipped folder of mod files to .minecraft\mods folder.  Crashes when try to start minecraft. 

Crash Report:
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/17/15 9:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/BlockEvent$BreakEvent
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:149)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:181)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:471)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:806)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/BlockEvent$BreakEvent
    at shadowmage.ancient_warfare.common.registry.AmmoRegistry.registerAmmoTypes(AmmoRegistry.java:59)
    at shadowmage.ancient_warfare.common.AWCore.preInit(AWCore.java:145)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:520)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.world.BlockEvent$BreakEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 39 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:171)
    ... 41 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 157435088 bytes (150 MB) / 234704896 bytes (223 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.2.881 Minecraft Forge 9.11.0.881 6 mods loaded, 6 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{6.4.2.881} [Forge Mod Loader](minecraftforge-9.11.0.881.jar) Unloaded->Constructed->Pre-initialized
    Forge{9.11.0.881} [Minecraft Forge](minecraftforge-9.11.0.881.jar) Unloaded->Constructed->Pre-initialized
    Erebus{v0.2.0a} [Erebus]([1.6.4] Erebus 0.2pre3) Unloaded->Constructed->Pre-initialized
    AncientWarfare{1.1.047-beta-MC164} [Ancient Warfare](Ancient-Warfare-Mod-1.6.4.zip) Unloaded->Constructed->Errored
    AncientStructures{1.1.047-beta-MC164} [Ancient Warfare Structures Module](Ancient-Warfare-Mod-1.6.4.zip) Unloaded->Constructed->Errored

**Comment by GotoLink** [comment]
Update Forge.
You are 84 versions late from the recommended for 1.6.4.
