### ISSUE TITLE
Engineering Station inventory periodically resets

### ISSUE THREAD

**Issue by aziel13** [P3pp3rF1y/AncientWarfare2#246]
On my Resonant Rise server I have been having a problem with the engineering station. Periodically the content of the inventory in the engineering station and auto crafting station is lost, including the research book.  This doesn't appear to happen when I unload the chunk or when the server is reset so Im not exactly how to replicate this issue. What usually happens is that I return to the table to craft something new and find there's nothing in it after being way for some time.

**Comment by polkziggy** [comment]
DItto. I have this same issue frequently. It does not appear to be related to chunk loading. At one point, I close the GUI, walked 15 blocks away, then returned to find it empty. I too am playing Resonant Rise 3.

**Comment by Pewmaymen** [comment]
This issue has the following stack trace in the server log when it happens:
[16:41:34] [Server thread/ERROR] [FML/]: A TileEntity engineering_station_tile(net.shadowmage.ancientwarfare.core.tile.TileEngineeringStation) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.core.research.ResearchTracker.hasPlayerCompleted(ResearchTracker.java:103) ~[ResearchTracker.class:?]
    at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.canPlayerCraft(AWCraftingManager.java:59) ~[AWCraftingManager.class:?]
    at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.findMatchingRecipe(AWCraftingManager.java:44) ~[AWCraftingManager.class:?]
    at net.shadowmage.ancientwarfare.core.tile.TileEngineeringStation.onLayoutMatrixChanged(TileEngineeringStation.java:97) ~[TileEngineeringStation.class:?]
    at net.shadowmage.ancientwarfare.core.tile.TileEngineeringStation.access$000(TileEngineeringStation.java:21) ~[TileEngineeringStation.class:?]
    at net.shadowmage.ancientwarfare.core.tile.TileEngineeringStation$2.func_75130_a(TileEngineeringStation.java:50) ~[TileEngineeringStation$2.class:?]
    at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81) ~[aae.class:?]
    at net.shadowmage.ancientwarfare.core.util.InventoryTools.readInventoryFromNBT(InventoryTools.java:599) ~[InventoryTools.class:?]
    at net.shadowmage.ancientwarfare.core.tile.TileEngineeringStation.func_145839_a(TileEngineeringStation.java:122) ~[TileEngineeringStation.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313) [mt.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

We were just hit by it.  Very disappointing to lose all your research.

**Comment by Pewmaymen** [comment]
Note that I am not on Resonant Rise.
