### ISSUE TITLE
Spawner block crash - unable to reopen world afterwards

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#248]
Mob Spawner block crash - unable to open world after placing mob spawner

Time: 18/03/15 21:08
Description: Ticking block entity

java.lang.IllegalArgumentException: n must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.shadowmage.ancientwarfare.structure.tile.SpawnerSettings.updateNormalMode(SpawnerSettings.java:136)
    at net.shadowmage.ancientwarfare.structure.tile.SpawnerSettings.onUpdate(SpawnerSettings.java:95)
    at net.shadowmage.ancientwarfare.structure.tile.TileAdvancedSpawner.func_145845_h(TileAdvancedSpawner.java:41)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.Random.nextInt(Unknown Source)
    at net.shadowmage.ancientwarfare.structure.tile.SpawnerSettings.updateNormalMode(SpawnerSettings.java:136)
    at net.shadowmage.ancientwarfare.structure.tile.SpawnerSettings.onUpdate(SpawnerSettings.java:95)
    at net.shadowmage.ancientwarfare.structure.tile.TileAdvancedSpawner.func_145845_h(TileAdvancedSpawner.java:41)

-- Block entity being ticked --
Details:
    Name: advanced_spawner_tile // net.shadowmage.ancientwarfare.structure.tile.TileAdvancedSpawner
    Block type: ID #1282 (tile.advanced_spawner // net.shadowmage.ancientwarfare.structure.block.BlockAdvancedSpawner)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (1916,98,1778), Chunk: (at 12,6,2 in 119,111; contains blocks 1904,0,1776 to 1919,255,1791), Region: (3,3; contains chunks 96,96 to 127,127, blocks 1536,0,1536 to 2047,255,2047)
    Actual block type: ID #1282 (tile.advanced_spawner // net.shadowmage.ancientwarfare.structure.block.BlockAdvancedSpawner)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: Builder World One Seven
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 626 Drop: 0
    Level seed: -3741348424273070587
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 2;7,59x1,3x3,2;1;stronghold,biome_1,village,decoration,dungeon,lake,mineshaft,lava_lake
    Level spawn location: World: (1728,72,1762), Chunk: (at 0,4,2 in 108,110; contains blocks 1728,0,1760 to 1743,255,1775), Region: (3,3; contains chunks 96,96 to 127,127, blocks 1536,0,1536 to 2047,255,2047)
    Level time: 6140735 game time, 7903310 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 25089 (now: false), thunder time: 2007 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1051554712 bytes (1002 MB) / 2399141888 bytes (2288 MB) up to 3340566528 bytes (3185 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 1 loaded mod(s)
          - MAtmos version r28 for 1.7.10
    LaunchWrapper: 26 active transformer(s)
          - Transformer:

**Comment by MohawkyMagoo** [comment]
Went into world using MCEdit and removed spawner blocks. World now reopens.

**Comment by GotoLink** [comment]
This is due to having both min and max delay the same value.
Easy fix.

**Comment by MohawkyMagoo** [comment]
Oh! Thanks for that!

**Comment by GotoLink** [comment]
Fixed.
