### ISSUE TITLE
Level-up, HP refresh and DamageIndicators issue

### ISSUE THREAD

**Issue by gstv87** [P3pp3rF1y/AncientWarfare2#27]
crash.
---- Minecraft Crash Report ----
// You're mean.

Time: 20/06/14 17:37
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at cpw.mods.fml.client.FMLClientHandler.getCurrentLanguage(FMLClientHandler.java:595)
    at cpw.mods.fml.common.FMLCommonHandler.getCurrentLanguage(FMLCommonHandler.java:520)
    at cpw.mods.fml.common.registry.LanguageRegistry.getStringLocalization(LanguageRegistry.java:59)
    at DamageIndicatorsMod.rendering.DIWordParticles.<init>(DIWordParticles.java:27)
    at DamageIndicatorsMod.core.DIEventBus.updateHealth(DIEventBus.java:124)
    at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:298)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_83_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:274)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1557)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:617)
    at net.minecraft.world.World.func_72866_a(World.java:2019)
    at net.minecraft.world.World.func_72870_g(World.java:1983)
    at net.minecraft.world.World.func_72939_s(World.java:1836)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:916)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.client.FMLClientHandler.getCurrentLanguage(FMLClientHandler.java:595)
    at cpw.mods.fml.common.FMLCommonHandler.getCurrentLanguage(FMLCommonHandler.java:520)
    at cpw.mods.fml.common.registry.LanguageRegistry.getStringLocalization(LanguageRegistry.java:59)
    at DamageIndicatorsMod.rendering.DIWordParticles.<init>(DIWordParticles.java:27)
    at DamageIndicatorsMod.core.DIEventBus.updateHealth(DIEventBus.java:124)
    at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:298)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_83_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:274)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1557)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:617)
    at net.minecraft.world.World.func_72866_a(World.java:2019)
    at net.minecraft.world.World.func_72870_g(World.java:1983)

-- Entity being ticked --
Details:
    Entity Type: AncientWarfareNpc.aw_npc_trader (net.shadowmage.ancientwarfare.npc.entity.NpcTrader)
    Entity ID: 1520732
    Entity Name: entity.AncientWarfareNpc.aw_npc_trader.name
    Entity's Exact location: 1324,50, 4,00, -701,50
    Entity's Block location: World: (1324,4,-702), Chunk: (at 12,0,2 in 82,-44; contains blocks 1312,0,-704 to 1327,255,-689), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
    Entity's Momentum: 0,00, -0,08, 0,00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1836)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Nighthawk'/1478, l='MpServer', x=1326,11, y=5,62, z=-703,59]]
    Chunk stats: MultiplayerChunkCache: 240, 249
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1332,4,-704), Chunk: (at 4,0,0 in 83,-44; contains blocks 1328,0,-704 to 1343,255,-689), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
    Level time: 6571 game time, 7571 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 18 total; [EntityCow['Cow'/133714, l='MpServer', x=1322,25, y=4,00, z=-745,16], EntityCow['Cow'/133713, l='MpServer', x=1322,75, y=4,00, z=-747,78], EntityCow['Cow'/133712, l='MpServer', x=1331,03, y=4,00, z=-743,94], EntityClientPlayerMP['Nighthawk'/1478, l='MpServer', x=1326,11, y=5,62, z=-703,59], EntityPig['Pig'/133703, l='MpServer', x=1279,50, y=4,00, z=-707,50], NpcTrader['entity.AncientWarfareNpc.aw_npc_trader.name'/1520732, l='MpServer', x=1324,50, y=4,00, z=-701,50], EntityPig['Pig'/133706, l='MpServer', x=1280,53, y=4,00, z=-709,16], EntityPig['Pig'/133704, l='MpServer', x=1274,25, y=4,00, z=-711,44], EntityPig['Pig'/133705, l='MpServer', x=1277,84, y=4,00, z=-714,94], EntityCow['Cow'/133711, l='MpServer', x=1333,88, y=4,00, z=-741,09], EntityChicken['Chicken'/133731, l='MpServer', x=1287,50, y=4,00, z=-634,50], EntityChicken['Chicken'/133732, l='MpServer', x=1290,50, y=4,00, z=-631,50], EntityChicken['Chicken'/133733, l='MpServer', x=1291,50, y=4,00, z=-628,50], EntityChicken['Chicken'/133734, l='MpServer', x=1288,50, y=4,00, z=-628,50], EntityChicken['Chicken'/133735, l='MpServer', x=1248,50, y=4,00, z=-712,50], EntityChicken['Chicken'/133736, l='MpServer', x=1248,50, y=4,00, z=-713,50], EntityChicken['Chicken'/133738, l='MpServer', x=1249,88, y=4,00, z=-717,66], EntityPig['Pig'/133739, l='MpServer', x=1249,50, y=4,00, z=-710,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:368)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2382)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:857)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows Vista (x86) version 6.0
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 277689496 bytes (264 MB) / 788307968 bytes (751 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1G
    AABB Pool Size: 302 (16912 bytes; 0 MB) allocated, 250 (14000 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.211.1121 Minecraft Forge 10.12.2.1121 Optifine OptiFine_1.7.2_HD_D1 22 mods loaded, 22 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.211.1121} [Forge Mod Loader](forge-1.7.2-10.12.2.1121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.2.1121} [Minecraft Forge](forge-1.7.2-10.12.2.1121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.1} [Not Enough Items](Not-Enough-Items-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.1.2} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfare{2.0.35-alpha-MC1.7.2} [Ancient Warfare Core](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareAutomation{2.0.35-alpha-MC1.7.2} [Ancient Warfare Automation](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareModeler{2.0.35-alpha-MC1.7.2} [Ancient Warfare Model Editor](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNEIPlugin{2.0.35-alpha-MC1.7.2} [Ancient Warfare NEI Plugin](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNpc{2.0.35-alpha-MC1.7.2} [Ancient Warfare NPCs](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareStructure{2.0.35-alpha-MC1.7.2} [Ancient Warfare Structures](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareVehicle{2.0.35-alpha-MC1.7.2} [Ancient Warfare Vehicles](ancientwarfare-2.0.35-alpha-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.2 v1.6.1} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.6.3} [BiblioCraft](BiblioCraft[1.6.3][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.883-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomSpawner{3.2.0.dev.R3} [DrZhark's CustomSpawner](CustomMobSpawner 3.2.0-DEV-R3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.1.1} [MapWriter](MapWriter-1.7.2-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    radixcore{1.1.1} [RadixCore](RadixCore-1.1.1_MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mca{4.0.3} [Minecraft Comes Alive](MCA-4.0.3_MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.2-Forge10.12.2.1121
    LWJGL: 2.9.0
    OpenGL: GeForce G 105M/PCI/SSE2 GL version 2.1.2, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: ~~ERROR~~ NullPointerException: null
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 128 (7168 bytes; 0 MB) allocated, 61 (3416 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

**Comment by shadowmage45** [comment]
at DamageIndicatorsMod.rendering.DIWordParticles.(DIWordParticles.java:27)
at DamageIndicatorsMod.core.DIEventBus.updateHealth(DIEventBus.java:124)
at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:298)

^^
Looks to be an issue with DamageIndicators rather than Ancient Warfare.  Please report the issue to that mods' author. More precisely, there is nothing I can even to do look into the issue, as DamageIndicators is closed-source (at least I cannot find a source-listing on their mod-page) -- so a fix will need to come from that mods' author.
