### ISSUE TITLE
kicks us from server when look at items in nei

### ISSUE THREAD

**Issue by henmaster101** [P3pp3rF1y/AncientWarfare2#288]
we get kicked from my server when nei looks at your blocks... no crash report. all it says is "a fatal error has occured, this connection is terminated

**Comment by GotoLink** [comment]
Game log please. There has to be some info you can give.

**Comment by MaikiOS** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/14/15 3:48 PM
Description: Colliding entity with block

java.lang.NullPointerException: Colliding entity with block
    at net.minecraft.entity.EntityList.func_75621_b(EntityList.java:229)
    at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.isHostileTowards(NpcFaction.java:80)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70693_a(NpcBase.java:803)
    at net.minecraft.entity.EntityLivingBase.getExpReward(EntityLivingBase.java:341)
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:358)
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1073)
    at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.func_70645_a(NpcFaction.java:106)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70097_a(NpcBase.java:360)
    at net.minecraft.block.BlockCactus.func_149670_a(BlockCactus.java:141)
    at net.minecraft.entity.Entity.func_145775_I(Entity.java:1063)
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1753)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2085)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1876)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:723)
    at net.minecraft.world.World.func_72866_a(World.java:2647)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
    at net.minecraft.world.World.func_72870_g(World.java:2600)
    at net.minecraft.world.World.func_72939_s(World.java:2412)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.EntityList.func_75621_b(EntityList.java:229)
    at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.isHostileTowards(NpcFaction.java:80)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70693_a(NpcBase.java:803)
    at net.minecraft.entity.EntityLivingBase.getExpReward(EntityLivingBase.java:341)
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:358)
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1073)
    at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.func_70645_a(NpcFaction.java:106)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70097_a(NpcBase.java:360)
    at net.minecraft.block.BlockCactus.func_149670_a(BlockCactus.java:141)

-- Block being collided with --
Details:
    Block type: ID #81 (tile.cactus // net.minecraft.block.BlockCactus)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-2443,66,-7352), Chunk: (at 5,4,8 in -153,-460; contains blocks -2448,0,-7360 to -2433,255,-7345), Region: (-5,-15; contains chunks -160,-480 to -129,-449, blocks -2560,0,-7680 to -2049,255,-7169)
Stacktrace:
    at net.minecraft.entity.Entity.func_145775_I(Entity.java:1063)

-- Entity being checked for collision --
Details:
    Entity Type: AncientWarfareNpc.desert.soldier (net.shadowmage.ancientwarfare.npc.entity.faction.NpcDesertSoldier)
    Entity ID: 19238
    Entity Name: Desert Native Soldier
    Entity's Exact location: -2443.24, 66.00, -7351.44
    Entity's Block location: World: (-2444,66,-7352), Chunk: (at 4,4,8 in -153,-460; contains blocks -2448,0,-7360 to -2433,255,-7345), Region: (-5,-15; contains chunks -160,-480 to -129,-449, blocks -2560,0,-7680 to -2049,255,-7169)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1753)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2085)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1876)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:723)
    at net.minecraft.world.World.func_72866_a(World.java:2647)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
    at net.minecraft.world.World.func_72870_g(World.java:2600)

-- Entity being ticked --
Details:
    Entity Type: AncientWarfareNpc.desert.soldier (net.shadowmage.ancientwarfare.npc.entity.faction.NpcDesertSoldier)
    Entity ID: 19238
    Entity Name: Desert Native Soldier
    Entity's Exact location: -2443.24, 66.00, -7351.44
    Entity's Block location: World: (-2444,66,-7352), Chunk: (at 4,4,8 in -153,-460; contains blocks -2448,0,-7360 to -2433,255,-7345), Region: (-5,-15; contains chunks -160,-480 to -129,-449, blocks -2560,0,-7680 to -2049,255,-7169)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2412)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
    Level name: world
    All players: 2 total; [EntityPlayerMP['marat129'/14060, l='world', x=-3574.68, y=47.00, z=-8954.80](marat129 at -3574.6776843970283,47.0,-8954.804748132337), EntityPlayerMP['Blood_Jack'/15928, l='world', x=-2441.58, y=66.00, z=-7350.13](Blood_Jack at -2441.5814938844437,66.0,-7350.132007370408)]
    Chunk stats: ServerChunkCache: 1139 Drop: 0
    Level seed: -3498797692375893756
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (740,64,1001), Chunk: (at 4,4,9 in 46,62; contains blocks 736,0,992 to 751,255,1007), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
    Level time: 1744315 game time, 1744315 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 61426 (now: false), thunder time: 38342 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4554842696 bytes (4343 MB) / 8490844160 bytes (8097 MB) up to 8490844160 bytes (8097 MB)
    JVM Flags: 2 total; -Xmx8192M -Xms8192M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
    FML: MCP v9.05 FML v7.10.88.1307 git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1307 42 mods loaded, 42 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.88.1307} [Forge Mod Loader](cauldron-1.7.10-1.1307.06.218-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1307} [Minecraft Forge](cauldron-1.7.10-1.1307.06.218-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgetsCore{1.1.6} [Witching Gadgets Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DungeonTools{2.1.0} [Dungeon Tools](1.7.10-DungeonTools-v2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfare{2.4.98-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.98-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareAutomation{2.4.98-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.98-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNEIPlugin{2.4.98-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.98-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNpc{2.4.98-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.98-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareStructure{2.4.98-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.98-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    nevermine{2.0.1} [AdventOfAscension](AoA-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Artifacts{1.1.1} [Artifacts](Artifacts-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1237-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.6-187} [Botania](Botania_r1.6-187.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.5} [Carpenter's Blocks](Carpenter's_Blocks_v3.3.5_-_MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.3.9.36} [Chisel 2](Chisel2-2.3.9.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    props{1.12} [Decocraft](Decocraft-v1.12b_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks_MoCreatures_Mod_v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Dynmap{2.1-104} [Dynmap](Dynmap-2.1-forge-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.10d} [Pam's HarvestCraft](Pam's_HarvestCraft_1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simplerecipes{1.7.2a} [Pam's Simple Recipes](Pam's_Simple_Recipes_1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    thaumcarpentry{0.0.1.5-1.7.10} [Thaumcarpentry](Thaumcarpentry-0.0.1.5-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicHorizons{1.1.1} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    torchLevers{1.4.1} [Torch Levers](TorchLeversV1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TravellersGear{1.16.2} [Traveller's Gear](TravellersGear-1.7.10-1.16.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgets{1.1.6} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HungerOverhaul{1.7.10-beta.6.jenkins70} [Hunger Overhaul](HungerOverhaul-1.7.10-beta.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 2 / 8; [EntityPlayerMP['marat129'/14060, l='world', x=-3574.68, y=47.00, z=-8954.80](marat129 at -3574.6776843970283,47.0,-8954.804748132337), EntityPlayerMP['Blood_Jack'/15928, l='world', x=-2441.58, y=66.00, z=-7350.13](Blood_Jack at -2441.5814938844437,66.0,-7350.132007370408)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by P3pp3rF1y** [comment]
closing, no NEI in 1.12 and haven't seen/heard about anything like this in there either.
