### ISSUE TITLE
Client Crash During Structure Generation

### ISSUE THREAD

**Issue by bcole90** [P3pp3rF1y/AncientWarfare2#343]
The game client crashes periodically when AW attempts to generate a structure.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/3/15 7:36 AM
Description: Exception in server tick loop

java.lang.RuntimeException: Caught exception while constructing template blocks: Vanilla Block Rule id: minecraft:stonebrick meta: 0 buildPass: 0
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.instantConstruction(StructureBuilder.java:105)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilderWorldGen.instantConstruction(StructureBuilderWorldGen.java:94)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler$StructureGenerationTicket.call(WorldGenTickHandler.java:132)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.genStructures(WorldGenTickHandler.java:90)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:49)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_37_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.placeBlock(StructureBuilder.java:151)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilderWorldGen.placeBlock(StructureBuilderWorldGen.java:59)
    at net.shadowmage.ancientwarfare.structure.template.plugin.default_plugins.block_rules.TemplateRuleVanillaBlocks.handlePlacement(TemplateRuleVanillaBlocks.java:59)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.placeRule(StructureBuilder.java:197)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.placeCurrentPosition(StructureBuilder.java:170)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.instantConstruction(StructureBuilder.java:100)
    ... 12 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 495821848 bytes (472 MB) / 1427988480 bytes (1361 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_B6 41 mods loaded, 41 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   AncientWarfare{2.4.106-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-285.jar) 
    UCHIJAAAA   AncientWarfareAutomation{2.4.106-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNEIPlugin{2.4.106-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNpc{2.4.106-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareStructure{2.4.106-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   MovingWorld{1.7.10-1.7.12B} [Moving World](movingworld-1.7.10-1.7.12B.jar) 
    UCHIJAAAA   ArchimedesShipsPlus{1.7.10-1.7.12} [Archimedes' Ships Plus](archimedesshipsplus-1.7.10-1.7.12.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Artifacts{1.1.2} [Artifacts](Artifacts-1.1.2.jar) 
    UCHIJAAAA   BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10] %281%29.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   Botania{r1.6-197} [Botania](Botania r1.6-197.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCHIJAAAA   chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) 
    UCHIJAAAA   props{2.0.2} [Decocraft](Decocraft-2.0.2_1.7.10.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   EnderZoo{1.7.10-1.0.11.28} [Ender Zoo](EnderZoo-1.7.10-1.0.11.28.jar) 
    UCHIJAAAA   enhancedportals{3.0.12} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.12.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](TConstruct-1.7.10-1.8.5.jar) 
    UCHIJAAAA   ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) 
    UCHIJAAAA   farlanders{1.2b} [The Farlanders](farlanders-1.7.10-v1.2b.jar) 
    UCHIJAAAA   GraveStone{2.12.3} [GraveStone](GraveStone-2.12.4.jar) 
    UCHIJAAAA   GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.1.1.jar) 
    UCHIJAAAA   HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.2.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-fairplay.jar) 
    UCHIJAAAA   movillages{1.2.1} [Mo' Villages](MoVillages-1.3.1.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJAAAA   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    CoFHCore: -[1.7.10]3.0.2-285
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Kosta_Lott'/178, l='New World', x=223.83, y=83.00, z=496.83]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jonathen-akens** [comment]
yes i can say i have received the same crash. I was playing around with MCHeli and when i was flying over a wooden structure, i was greeted not so kindly by this crash log. http://pastebin.com/S1igAEzB
at the time of THIS crash i WAS using optifine, i have removed optifine, reloaded the game and the same thing happened thanks for the help in advance :D

Edit: Converted Tired ramblings into an English that could be read :smile:
