### ISSUE TITLE
internal server error with structure builder

### ISSUE THREAD

**Issue by BLAKOUT13** [P3pp3rF1y/AncientWarfare2#349]
```
   So when i use the structure builder and sometimes the structure scanner it gives me an internal server error. It only happens when i have the structure builder in my hand and my hand is pointed at a block in range that i can break/ place an object on (so like 4-5 blocks) when i right click to open the menu it gives me a message saying internal server error. Im not sure if this is a bug or something i am doing wrong but if you could help that would be great.
```

**Comment by GotoLink** [comment]
Crash report would be nice.

**Comment by BLAKOUT13** [comment]
[15:03:23] [Server thread/INFO]: Send data to BLAKOUT13
[15:03:23] [Server thread/INFO]: Send data to BLAKOUT13
[15:03:23] [Server thread/INFO]: Send data to BLAKOUT13
[15:03:23] [Server thread/INFO]: Send data to BLAKOUT13
[15:03:28] [Server thread/INFO]: [DaFlightManagerBukkit] DaFlight query received from BLAKOUT13
[15:03:30] [Server thread/INFO]: BLAKOUT13 issued server command: /we cui
[15:03:43] [Server thread/WARN]: Failed to handle packet for /10.0.0.187:54067
java.lang.NullPointerException
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:946) ~[nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[15:03:43] [Server thread/INFO]: BLAKOUT13 lost connection: Internal server error
[15:03:43] [Server thread/INFO]: BLAKOUT13 left the game.

**Comment by BLAKOUT13** [comment]
Any luck?

It also says internal server error with the backpacks, routing orders and items like those.

**Comment by GotoLink** [comment]
Update ? It sounds like you use an old version of the mod, but i can't tell for sure because you cropped the crash log.
