### ISSUE TITLE
Research book closing client

### ISSUE THREAD

**Issue by distantgoth** [P3pp3rF1y/AncientWarfare2#364]
I can craft all items, but when I go to open the research book it closes the client with 'Internal server error' I've tried myself (admin) and I've also tried a builder on my server(server not live yet) and its not working.

**Comment by Sandriell** [comment]
Is there a crash log? And what version of AW are you using?

**Comment by distantgoth** [comment]
There's no crash log, it just closes the game to main menu. The Version is 2.4 107 full beta. It only seems to do it with the research book.

Sent from my Samsung device

-------- Original message --------

**Comment by GotoLink** [comment]
There is always a log. You should have a /logs folder.

**Comment by distantgoth** [comment]
Hey, been looking on the server
The only thing it shows up on the log is:
[22:30:01] [Server thread/WARN]: Failed to handle packet for /86.146.117.207:51392
java.lang.NullPointerException
 at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:918) ~[nh.class:?]
 at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
 at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
 at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
 at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
 at java.lang.Thread.run(Unknown Source) [?:1.7.0]
[22:30:01] [Server thread/INFO]: distantgoth lost connection: Internal server error

This happens on the server log, when the research book is opened and closes my client

Date: Sat, 8 Aug 2015 09:01:54 -0700

**Comment by distantgoth** [comment]
A update on this issue:
after further testing, I cant right click using ethier the Upkeep order, Work orders or the Research book.
It just shuts the game back to main menu with 'Internal Server Error'
Yet to get a crash report as its not crashing the game just shutting it back to main menu were i can press Multi-player and rejoin server.

**Comment by GotoLink** [comment]
Do you also get it with the combat order and structure scanner item ?
I am looking for a pattern here.

**Comment by distantgoth** [comment]
The structure scanner works however structure builder don't, combat order doesn't work they both throw up the internal server error

**Comment by distantgoth** [comment]
I have been looking at it further and noticed if I'm in creative mode I can right click to register the Research book and then I can open it.
But if I go into survival mode it throws the 'Internal Server Error'

**Comment by GotoLink** [comment]
[Experimental build here](http://www.mediafire.com/download/nwpcrrd0n2bw26b/ancientwarfare-2.4.109-beta-MC1.7.10-FULL.jar)
Please try it and report if you have or not the issue still.
You might also want to try build 108 either way.

**Comment by distantgoth** [comment]
Just to confirm the issue with the research book has been sorted :D
Thanks, I will test out all the other bits a some point soon :)

**Comment by GotoLink** [comment]
Thanks for reporting back :)
