### ISSUE TITLE
NullPointerException in GuiContainerBase

### ISSUE THREAD

**Issue by diamondq** [P3pp3rF1y/AncientWarfare2#378]
During connection to a world, it occasionally crashes with this exception. This is against 2.4.104 for MC 1.7.10. Since this is included as part of the Resonant Rise mod pack, it can't be easily upgraded. It appears to be a timing issue since the mc or thePlayer fields are temporarily null during the first few ticks.

```
java.lang.NullPointerException
    at net.minecraft.client.gui.inventory.GuiContainer.func_73876_c(GuiContainer.java:698)
    at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_73876_c(GuiContainerBase.java:199)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Sandriell** [comment]
There is nothing preventing you from updating the mod manually. I currently use RR3 myself, and have updated to the latest 111 version without any issue.

As with updating any mod though, backup beforehand to be safe.

**Comment by GotoLink** [comment]
Not ancient warfare responsibility. If something make mc or thePlayer fields null when this line is reached, it is impossible to fix. (And incompatible with vanilla too)
Please find the culprit mod within your mod pack.
Eventually blame the mod pack "maker" for not doing the tests he is supposed to.
