### ISSUE TITLE
Not a report. just a note re: NPC vanishing on relog

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#39]
NPC vanished on relog again. Letting you know what was in my log at the time.

[02:01:18] [Client thread/ERROR] [FML]: Unable to determine registrant mod for codechicken.lib.render.TextureUtils@7926303b. This is a critical error and should be impossible
java.lang.Throwable
at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:42) [EventBus.class:?]
at codechicken.lib.render.TextureUtils.<clinit>(TextureUtils.java:33) [TextureUtils.class:?]
at codechicken.nei.SpawnerRenderer.renderInventoryItem(SpawnerRenderer.java:39) [SpawnerRenderer.class:?]
at codechicken.nei.SpawnerRenderer.renderItem(SpawnerRenderer.java:81) [SpawnerRenderer.class:?]
at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183) [ForgeHooksClient.class:?]
at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563) [bny.class:?]
at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:200) [GuiContainerManager.class:?]
at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:190) [GuiContainerManager.class:?]
at codechicken.nei.ItemPanel.draw(ItemPanel.java:123) [ItemPanel.class:?]
at codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:196) [LayoutManager.class:?]
at codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:400) [GuiContainerManager.class:?]
at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120) [bex.class:?]
at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38) [bfo.class:?]
at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bfu.class:?]
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1352) [blt.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989) [bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]

I'm too tired tonight to even read it properly or look into whether it's due to Optifine or something else at my end. I shouldn't be using Optifine, I know. Will remove it tomorrow before logging in again.

**Comment by Dulciphi** [comment]
NPC missing on relog a 3rd time. No Optifine this time. 

Time was 22:42:58 my time, Aug 1. GMT + 10 hours.

**Comment by shadowmage45** [comment]
Aye, this was apparently related to a strange client/server issue -- I was referencing a client-side only code about 3-4 calls deep, and it was still throwing errors (even though it should have not triggered that code-path due to if statements).

Have moved all necessary calls into a proxy to ensure there is no client-server class-loading issues.
