### ISSUE TITLE
AW2 crashing when placing/spawning NPC

### ISSUE THREAD

**Issue by TankWarDog** [P3pp3rF1y/AncientWarfare2#396]
Whenever I spawn an NPC, my game shutdown. I'm currently playing it on RR3.  Any ideas or suggestions?

**Comment by Sandriell** [comment]
Update to the latest version of AW2. There is no harm in manually updating mods in a modpack.

**Comment by TankWarDog** [comment]
Whenever I spawn an NPC, my game shutdown. I'm currently playing it on RR3.  Any ideas or suggestions?

**Comment by TankWarDog** [comment]
Here's from the last crash....just now.

[29/9/2015 22:58:49 PM] [Server thread/ERROR]: Encountered an unexpected exception
[29/9/2015 22:58:49 PM] net.minecraft.util.ReportedException: Ticking memory connection
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[29/9/2015 22:58:49 PM] Caused by: java.lang.NullPointerException
[29/9/2015 22:58:49 PM]     at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:336) ~[mx.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) ~[nh.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
[29/9/2015 22:58:49 PM]     ... 5 more
[29/9/2015 22:58:49 PM] [Server thread/ERROR]: This crash report has been saved to: **USERSDIR**\Instances\ResonantRisewmapwogrim\crash-reports\crash-2015-09-29_22.58.49-server.txt
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Stopping server
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving players
[29/9/2015 22:58:49 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[29/9/2015 22:58:49 PM] // This doesn't make any sense!
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] Time: 9/29/15 10:58 PM
[29/9/2015 22:58:49 PM] Description: Ticking memory connection
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] java.lang.NullPointerException: Ticking memory connection
[29/9/2015 22:58:49 PM]     at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:336)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[29/9/2015 22:58:49 PM] ---------------------------------------------------------------------------------------
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] -- Head --
[29/9/2015 22:58:49 PM] Stacktrace:
[29/9/2015 22:58:49 PM]     at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:336)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] -- Ticking connection --
[29/9/2015 22:58:49 PM] Details:
[29/9/2015 22:58:49 PM]     Connection: net.minecraft.network.NetworkManager@30e976b7
[29/9/2015 22:58:49 PM] Stacktrace:
[29/9/2015 22:58:49 PM]     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[29/9/2015 22:58:49 PM]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[29/9/2015 22:58:49 PM] 
[29/9/2015 22:58:49 PM] -- System Details --
[29/9/2015 22:58:49 PM] Details:
[29/9/2015 22:58:49 PM]     Minecraft Version: 1.7.10
[29/9/2015 22:58:49 PM]     Operating System: Windows 7 (amd64) version 6.1
[29/9/2015 22:58:49 PM]     Java Version: 1.8.0_45, Oracle Corporation
[29/9/2015 22:58:49 PM]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[29/9/2015 22:58:49 PM]     Memory: 1147737048 bytes (1094 MB) / 3419062272 bytes (3260 MB) up to 4260102144 bytes (4062 MB)
[29/9/2015 22:58:49 PM]     Mod Pack: Unknown / None
[29/9/2015 22:58:49 PM]     LiteLoader Mods: 2 loaded mod(s)
[29/9/2015 22:58:49 PM]           - VoxelMap version 1.5.13
[29/9/2015 22:58:49 PM]           - Mouse Tweaks version 2.4.4
[29/9/2015 22:58:49 PM]     LaunchWrapper: 53 active transformer(s)
[29/9/2015 22:58:49 PM]           - Transformer: logisticspipes.asm.LogisticsPipesClassInjector
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
[29/9/2015 22:58:49 PM]           - Transformer: squeek.applecore.asm.TransformerModuleHandler
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[29/9/2015 22:58:49 PM]           - Transformer: net.minecraftforge.classloading.FluidIdTransformer
[29/9/2015 22:58:49 PM]           - Transformer: appeng.transformer.asm.ASMIntegration
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.lib.asm.ClassHeirachyManager
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.core.asm.TweakTransformer
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.core.asm.DelegatedTransformer
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.core.asm.DefaultImplementationTransformer
[29/9/2015 22:58:49 PM]           - Transformer: fastcraft.asm.FastCraftTransformer
[29/9/2015 22:58:49 PM]           - Transformer: mods.immibis.core.impl.MultiInterfaceClassTransformer
[29/9/2015 22:58:49 PM]           - Transformer: mods.immibis.core.impl.TraitTransformer
[29/9/2015 22:58:49 PM]           - Transformer: mods.immibis.core.multipart.MultipartCoreHookTransformer
[29/9/2015 22:58:49 PM]           - Transformer: invtweaks.forge.asm.ContainerTransformer
[29/9/2015 22:58:49 PM]           - Transformer: logisticspipes.asm.LogisticsClassTransformer
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.nei.asm.NEITransformer
[29/9/2015 22:58:49 PM]           - Transformer: openeye.asm.MultiTransformer
[29/9/2015 22:58:49 PM]           - Transformer: stevesaddons.asm.StevesAddonsTransformer
[29/9/2015 22:58:49 PM]           - Transformer: thaumic.tinkerer.preloader.AccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: schmoller.tubes.asm.MinecraftTransformer
[29/9/2015 22:58:49 PM]           - Transformer: portablejim.veinminer.asm.ItemInWorldManagerTransformer
[29/9/2015 22:58:49 PM]           - Transformer: openmods.core.OpenModsClassTransformer
[29/9/2015 22:58:49 PM]           - Transformer: openblocks.asm.OpenBlocksClassTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: appeng.transformer.asm.ASMTweaker
[29/9/2015 22:58:49 PM]           - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cofh.asm.CoFHAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: invtweaks.forge.asm.ITAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: logisticspipes.asm.LogisticsAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: stevesaddons.asm.StevesAddonsTransformer
[29/9/2015 22:58:49 PM]           - Transformer: thaumic.tinkerer.preloader.AccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cofh.asm.CoFHClassTransformer
[29/9/2015 22:58:49 PM]           - Transformer: lumien.randomthings.Transformer.RTClassTransformer
[29/9/2015 22:58:49 PM]           - Transformer: tterrag.core.common.transform.TTCoreTransformer
[29/9/2015 22:58:49 PM]           - Transformer: tterrag.core.common.transform.TTCoreTransformerClient
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
[29/9/2015 22:58:49 PM]           - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
[29/9/2015 22:58:49 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
[29/9/2015 22:58:49 PM]     JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:MetaspaceSize=256M
[29/9/2015 22:58:49 PM]     AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[29/9/2015 22:58:49 PM]     IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
[29/9/2015 22:58:49 PM]     FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 241 mods loaded, 241 mods active
[29/9/2015 22:58:49 PM]     States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
[29/9/2015 22:58:49 PM]     UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   Aroma1997Core{1.0.2.15} [Aroma1997Core](AROMA1997CORE-1.7.10-1.0.2.15.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   ivtoolkit{IvToolkit} [1.2](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NOTENOUGHITEMS-1.7.10-1.0.5.111-UNIVERSAL.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   OpenEye{0.6} [OpenEye](OPENEYE-0.6-1.7.10-SNAPSHOT-141.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   TubesCore{${version}} [Tubes Core](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   VeinMiner_coremod{0.27.1_build.unknown} [Core mod](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   debug{1.0} [debug](DENSEORES-1.6.2.jar) 
[29/9/2015 22:58:49 PM]     UCHIJAAAA   Pistronics2{0.5.1} [Pistronics 2](1.7.10-PISTRONICS2-V0.5.8.jar) 
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Nether
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Underdark
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Spirit World
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Torment
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Mirror
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/The Outer Lands
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Bedrock
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/The Last Millenium
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Twilight Forest
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/Mining World
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/CompactMachinesWorld
[29/9/2015 22:58:49 PM] [Server thread/INFO]: Saving chunks for level 'The I'/SpectreWorld
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension 0
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -1
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -100
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -37
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -38
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -39
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -42
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -19
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension -112
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension 7
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension 6
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension 3
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Unloading dimension 2
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Applying holder lookups
[29/9/2015 22:58:50 PM] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[29/9/2015 22:58:50 PM] [Server thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[29/9/2015 22:58:50 PM] [Server thread/WARN] [FML]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[29/9/2015 22:58:50 PM] [Server thread/WARN] [FML]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[29/9/2015 22:58:50 PM] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: Holder lookups applied
[29/9/2015 22:58:50 PM] [Server thread/INFO] [Compact Machines]: Unregistering dimension 3 on client side
[29/9/2015 22:58:50 PM] [22:58:50] [pool-6-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to **USERSDIR**\Instances\ResonantRisewmapwogrim\saves\The I\enderio\dimensionalTransceiver.json
[29/9/2015 22:58:50 PM] [Server thread/INFO] [ProjectE]: Completed server-stop actions.
[29/9/2015 22:58:50 PM] [Server thread/INFO] [mcjty.rftools.RFTools]: RFTools: server is stopping. Shutting down gracefully
[29/9/2015 22:58:50 PM] [Server thread/INFO] [mcjty.rftools.RFTools]: Cleaning up RFTools dimensions
[29/9/2015 22:58:50 PM] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[29/9/2015 22:58:50 PM] [Client thread/INFO] [FML]: Server terminated.
[29/9/2015 22:58:50 PM] Checking for updated files!
[29/9/2015 22:58:51 PM] Updates found!
[29/9/2015 22:58:51 PM] Checking for updated files!
[29/9/2015 22:58:51 PM] Updates found!
[29/9/2015 22:58:51 PM] Downloading Launcher File packs.json
[29/9/2015 22:58:52 PM] Finished downloading updated files!
[29/9/2015 22:58:52 PM] Loading Language: English

**Comment by TankWarDog** [comment]
ANCIENTWARFARE-2.4.106-BETA-MC1.7.10-FULL is the version I'm using.  Does this need updated?

**Comment by GotoLink** [comment]
2.4.113 is latest.
This bug had been fixed in between.

**Comment by TankWarDog** [comment]
thank you

**Comment by HiddenSquid** [comment]
Im having the same problem in that my game crashes every time I place an NPC. My RR3 pack is still using 2.4.106 but it hasn't given me the option to update. Can anyone tell me how to update to 2.4.113

**Comment by TankWarDog** [comment]
Just drop the current in the mod folder

R/S
F. S. Kancir III
L.L.C.R.

"Sæpius Provocaverat, Semper Fidelis, Fratres in Aeternum"
