### ISSUE TITLE
Client-crash on placing civic worksite

### ISSUE THREAD

**Issue by shadowmage45** [P3pp3rF1y/AncientWarfare2#47]
net.minecraft.util.ReportedException: Rendering Block Entity
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:107) ~[bmk.class:?]
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92) ~[bmk.class:?]
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483) ~[bma.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1337) ~[blt.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_45]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.automation.render.RenderTileWorksite.renderBoundingBox(RenderTileWorksite.java:48) ~[RenderTileWorksite.class:?]
    at net.shadowmage.ancientwarfare.automation.render.RenderTileWorksite.func_147500_a(RenderTileWorksite.java:38) ~[RenderTileWorksite.class:?]
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100) ~[bmk.class:?]
    ... 21 more

**Comment by alphaalphaalpha2** [comment]
crash report?
