### ISSUE TITLE
Acient Warfare Mod for MC 1.12.2 crashes when placing storage block in storage stystem

### ISSUE THREAD

**Issue by Cy-Duck** [P3pp3rF1y/AncientWarfare2#539]
Heres the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (Backpacks-Mod-by-Brad16840-1.12.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 11/25/17 7:28 AM
Description: Ticking block entity

java.lang.AbstractMethodError: net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouse.getPos()Lnet/minecraft/util/math/BlockPos;
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileControlled.setController(TileControlled.java:82)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.addStorageTile(TileWarehouseBase.java:326)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.addControlledTile(TileWarehouseBase.java:402)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.scanForInitialTiles(TileWarehouseBase.java:273)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.updateWorksite(TileWarehouseBase.java:255)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.TileWorksiteBase.func_73660_a(TileWorksiteBase.java:170)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileControlled.setController(TileControlled.java:82)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.addStorageTile(TileWarehouseBase.java:326)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.addControlledTile(TileWarehouseBase.java:402)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.scanForInitialTiles(TileWarehouseBase.java:273)
	at net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouseBase.updateWorksite(TileWarehouseBase.java:255)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.TileWorksiteBase.func_73660_a(TileWorksiteBase.java:170)

-- Block entity being ticked --
Details:
	Name: minecraft:warehouse_control_tile // net.shadowmage.ancientwarfare.automation.tile.warehouse2.TileWarehouse
	Block type: ID #265 (tile.warehouse_control // net.shadowmage.ancientwarfare.automation.block.BlockWorksiteBase)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (51,69,-3), Chunk: (at 3,4,13 in 3,-1; contains blocks 48,0,-16 to 63,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #265 (tile.warehouse_control // net.shadowmage.ancientwarfare.automation.block.BlockWorksiteBase)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: just another test
	All players: 1 total; [EntityPlayerMP['Cy_Duck'/627, l='just another test', x=51.50, y=69.00, z=-3.50]]
	Chunk stats: ServerChunkCache: 1119 Drop: 0
	Level seed: -8986251667210661129
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (48,64,-4), Chunk: (at 0,4,12 in 3,-1; contains blocks 48,0,-16 to 63,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 94 game time, 94 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 128870 (now: false), thunder time: 123057 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 343192104 bytes (327 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.0.2552 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version        | Source                                  | Signature                                |
	|:--------- |:------------------------ |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                      | 9.42           | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99      | forge-1.12.2-14.23.0.2552.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.0.2552   | forge-1.12.2-14.23.0.2552.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | backpacks16840           | 3.3.2          | Backpacks-Mod-by-Brad16840-1.12.2.jar   | None                                     |
	| UCHIJAAAA | mercurius_updater        | 1.0            | MercuriusUpdater-1.12.2.jar             | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.1.3.313      | CodeChickenLib-1.12.1.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | ancientwarfareautomation | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | jei                      | 4.8.0.114      | Just-Enough-Items-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAA | nei                      | ${mod_version} | Not-Enough-Items-1.12.2-Recommended.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | uncraftingtable          | 1.8-beta6      | Uncrafting-Table-Mod-1.12.1.jar         | None                                     |
	| UCHIJAAAA | xaerominimap             | 1.13.9         | Xaeros-Minimap-Mod-1.12.jar             | None                                     |

	Loaded coremods (and transformers): 
BCModPlugin (Backpacks-Mod-by-Brad16840-1.12.2.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Cy_Duck'/627, l='just another test', x=51.50, y=69.00, z=-3.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by P3pp3rF1y** [comment]
Please try with the latest build ancientwarfare-1.12.2-2.4.11 (or with the latest code because you seem to be building it from repo) this was resolved 2 days ago.
