### ISSUE TITLE
1.12.2-2.4.24 beta crash

### ISSUE THREAD

**Issue by tombo512** [P3pp3rF1y/AncientWarfare2#553]
Hello.
Thanks for your immediate update!
I tried new beta file but it crashed.
Log message is below.

> [23:10:23]
 [Server thread/ERROR]: Encountered an unexpected exception
ava.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
        at net.shadowmage.ancientwarfare.structure.block.BlockStructureBuilder.func_149666_a(BlockStructureBuilder.java:40) ~[BlockStructureBuilder.class:?]
        at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:149) ~[ahb.class:?]
        at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38) ~[MCItemUtils.class:?]
        at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63) ~[BracketHandlerItem.class:?]
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:39) ~[CommonEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_CommonEventHandler_registerRecipes_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746) ~[GameData.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622) ~[CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        ... 17 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        ... 17 more
[23:10:23] [Server thread/ERROR]: This crash report has been saved to: /home/hirota/Forge1.12.2/./crash-reports/crash-2017-12-05_23.10.23-server.txt
[23:10:23] [Server thread/INFO]: Stopping server
[23:10:23] [Server thread/INFO]: Saving worlds
[23:10:23] [Server Shutdown Thread/INFO]: Stopping server
[23:10:23] [Server Shutdown Thread/INFO]: Saving worlds

**Comment by tombo512** [comment]
crash report

>---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 17/12/05 23:13
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
        at net.shadowmage.ancientwarfare.structure.block.BlockStructureBuilder.func_149666_a(BlockStructureBuilder.java:40)
        at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:149)
        at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38)
        at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:39)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717)
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
        ... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 2.6.32-696.13.2.el6.x86_64
        Java Version: 1.8.0_151, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1539927000 bytes (1468 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
        JVM Flags: 2 total; -Xmx2048M -Xms2048M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.1.2555 15 mods loaded, 15 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored


        | State | ID                                        | Version      | Source                                      | Signature
         |
        |:----- |:----------------------------------------- |:------------ |:------------------------------------------- |:--------------------------------
-------- |
        | UCH   | minecraft                                 | 1.12.2       | minecraft.jar                               | None
         |
        | UCH   | mcp                                       | 9.42         | minecraft.jar                               | None
         |
        | UCH   | FML                                       | 8.0.99.99    | minecraftforge.jar                          | e3c3d50c7c986df74c645c0ac5463974
1c90a557 |
        | UCH   | forge                                     | 14.23.1.2555 | minecraftforge.jar                          | e3c3d50c7c986df74c645c0ac5463974
1c90a557 |
        | UCH   | codechickenlib                            | 3.1.3.313    | CodeChickenLib-1.12-3.1.3.313-universal.jar | f1850c39b2516232a2108a7bd84d1cb5
df93b261 |
        | UCH   | ancientwarfare                            | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfareautomation                  | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfarenpc                         | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfarestructure                   | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | bibliocraft                               | 2.4.3        | BiblioCraft-Mod-1.12.jar                    | None
         |
        | UCH   | crafttweaker                              | 4.0.10       | CraftTweaker2-1.12-4.0.10.jar               | None
         |
        | UCH   | crafttweakerjei                           | 2.0.0        | CraftTweaker2-1.12-4.0.10.jar               | None
         |
        | UCH   | net.minecraft.scalar.cutall.mod_cutallsmp | 2.5.2        | CutAllSMP_v2.5.2.zip                        | None
         |
        | UCH   | spawnchecker                              | 2.7.7.137    | SpawnChecker-2.7.7.137.jar                  | 26e70d58815b73cd7c6c865fe091672f
79070a35 |
        | UCH   | spawnchecker.presetmode                   | 2.7.7.137    | SpawnChecker-2.7.7.137.jar                  | 26e70d58815b73cd7c6c865fe091672f
79070a35 |

        Loaded coremods (and transformers):
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by tombo512** [comment]
crash report
>---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 17/12/05 23:13
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
        at net.shadowmage.ancientwarfare.structure.block.BlockStructureBuilder.func_149666_a(BlockStructureBuilder.java:40)
        at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:149)
        at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38)
        at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:39)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717)
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
        ... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 2.6.32-696.13.2.el6.x86_64
        Java Version: 1.8.0_151, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1539927000 bytes (1468 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
        JVM Flags: 2 total; -Xmx2048M -Xms2048M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.1.2555 15 mods loaded, 15 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored


        | State | ID                                        | Version      | Source                                      | Signature
         |
        |:----- |:----------------------------------------- |:------------ |:------------------------------------------- |:--------------------------------
-------- |
        | UCH   | minecraft                                 | 1.12.2       | minecraft.jar                               | None
         |
        | UCH   | mcp                                       | 9.42         | minecraft.jar                               | None
         |
        | UCH   | FML                                       | 8.0.99.99    | minecraftforge.jar                          | e3c3d50c7c986df74c645c0ac5463974
1c90a557 |
        | UCH   | forge                                     | 14.23.1.2555 | minecraftforge.jar                          | e3c3d50c7c986df74c645c0ac5463974
1c90a557 |
        | UCH   | codechickenlib                            | 3.1.3.313    | CodeChickenLib-1.12-3.1.3.313-universal.jar | f1850c39b2516232a2108a7bd84d1cb5
df93b261 |
        | UCH   | ancientwarfare                            | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfareautomation                  | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfarenpc                         | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfarestructure                   | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | bibliocraft                               | 2.4.3        | BiblioCraft-Mod-1.12.jar                    | None
         |
        | UCH   | crafttweaker                              | 4.0.10       | CraftTweaker2-1.12-4.0.10.jar               | None
         |
        | UCH   | crafttweakerjei                           | 2.0.0        | CraftTweaker2-1.12-4.0.10.jar               | None
         |
        | UCH   | net.minecraft.scalar.cutall.mod_cutallsmp | 2.5.2        | CutAllSMP_v2.5.2.zip                        | None
         |
        | UCH   | spawnchecker                              | 2.7.7.137    | SpawnChecker-2.7.7.137.jar                  | 26e70d58815b73cd7c6c865fe091672f
79070a35 |
        | UCH   | spawnchecker.presetmode                   | 2.7.7.137    | SpawnChecker-2.7.7.137.jar                  | 26e70d58815b73cd7c6c865fe091672f
79070a35 |

        Loaded coremods (and transformers):
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by tombo512** [comment]
crash report

>--- Minecraft Crash Report ----
WARNING: coremods are present:
Contact their authors BEFORE contacting forge
// Why did you do that?
Time: 17/12/05 23:13
Description: Exception in server tick loop
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
        at net.shadowmage.ancientwarfare.structure.block.BlockStructureBuilder.func_149666_a(BlockStructureBuilder.java:40)
        at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:149)
        at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38)
        at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:39)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717)
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
        ... 19 more
A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 2.6.32-696.13.2.el6.x86_64
        Java Version: 1.8.0_151, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1539927000 bytes (1468 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
        JVM Flags: 2 total; -Xmx2048M -Xms2048M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.1.2555 15 mods loaded, 15 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        | State | ID                                        | Version      | Source                                      | Signature
         |
        |:----- |:----------------------------------------- |:------------ |:------------------------------------------- |:--------------------------------
-------- |
        | UCH   | minecraft                                 | 1.12.2       | minecraft.jar                               | None
         |
        | UCH   | mcp                                       | 9.42         | minecraft.jar                               | None
         |
        | UCH   | FML                                       | 8.0.99.99    | minecraftforge.jar                          | e3c3d50c7c986df74c645c0ac5463974
1c90a557 |
        | UCH   | forge                                     | 14.23.1.2555 | minecraftforge.jar                          | e3c3d50c7c986df74c645c0ac5463974
1c90a557 |
        | UCH   | codechickenlib                            | 3.1.3.313    | CodeChickenLib-1.12-3.1.3.313-universal.jar | f1850c39b2516232a2108a7bd84d1cb5
df93b261 |
        | UCH   | ancientwarfare                            | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfareautomation                  | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfarenpc                         | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | ancientwarfarestructure                   | @VERSION@    | ancientwarfare-1.12.2-2.4.24.jar            | None
         |
        | UCH   | bibliocraft                               | 2.4.3        | BiblioCraft-Mod-1.12.jar                    | None
         |
        | UCH   | crafttweaker                              | 4.0.10       | CraftTweaker2-1.12-4.0.10.jar               | None
         |
        | UCH   | crafttweakerjei                           | 2.0.0        | CraftTweaker2-1.12-4.0.10.jar               | None
         |
        | UCH   | net.minecraft.scalar.cutall.mod_cutallsmp | 2.5.2        | CutAllSMP_v2.5.2.zip                        | None
         |
        | UCH   | spawnchecker                              | 2.7.7.137    | SpawnChecker-2.7.7.137.jar                  | 26e70d58815b73cd7c6c865fe091672f
79070a35 |
        | UCH   | spawnchecker.presetmode                   | 2.7.7.137    | SpawnChecker-2.7.7.137.jar                  | 26e70d58815b73cd7c6c865fe091672f
79070a35 |
        Loaded coremods (and transformers):
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by P3pp3rF1y** [comment]
Looks like you will only get this crash with craft tweaker, but that part of the code could potentially be accessed by some other mod that tries to load sub blocks on dedicated server as well. So I have added a bit of code so that this works with those.

**Comment by P3pp3rF1y** [comment]
Could you test this build and see if that works for you? https://bintray.com/p3pp3rf1y/maven/download_file?file_path=ancientwarfare-1.12.2-2.4.26unstable.jar

**Comment by tombo512** [comment]
It seems ok, and scanning structures is working fine!
Thank you :-)

**Comment by P3pp3rF1y** [comment]
This is resolved in the latest release
