### ISSUE TITLE
Crash trying to use adjacent storage on research station [can't restart server]

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#584]
I was attempting to have the research station use the warehouse. I clicked the checkbox and then when to click the directions.

(I was going to get you a screen shot but I can't get the server back up ... see below.)

Clicking the "North" button on the left caused the below crash.

```
[20:45:09] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.tryStartNextResearch(TileResearchStation.java:245) ~[TileResearchStation.class:?]
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_73660_a(TileResearchStation.java:168) ~[TileResearchStation.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
```

Full report:

```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/28/18 8:45 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.tryStartNextResearch(TileResearchStation.java:245)
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_73660_a(TileResearchStation.java:168)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.tryStartNextResearch(TileResearchStation.java:245)
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_73660_a(TileResearchStation.java:168)

-- Block entity being ticked --
Details:
	Name: minecraft:research_station_tile // net.shadowmage.ancientwarfare.core.tile.TileResearchStation
	Block type: ID #254 (tile.research_station // net.shadowmage.ancientwarfare.core.block.BlockResearchStation)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-218,75,226), Chunk: (at 6,4,2 in -14,14; contains blocks -224,0,224 to -209,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #254 (tile.research_station // net.shadowmage.ancientwarfare.core.block.BlockResearchStation)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['WadeW78'/388, l='world', x=-219.34, y=75.00, z=226.13]]
	Chunk stats: ServerChunkCache: 461 Drop: 0
	Level seed: 5045379516656213199
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options:
	Level spawn location: World: (-244,64,248), Chunk: (at 12,4,8 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6471710 game time, 7391102 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19686 (now: false), thunder time: 14782 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.13.0-31-generic
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 581114032 bytes (554 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2604 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version      | Source                                        | Signature                                |
	|:--------- |:------------------------ |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99    | forge-1.12.2-14.23.1.2604-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.1.2604 | forge-1.12.2-14.23.1.2604-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib           | 3.1.5.331    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | ancientwarfareautomation | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | jei                      | 4.8.0.114    | jei_1.12.2-4.8.0.114.jar                      | None                                     |
	| UCHIJAAAA | mercurius_updater        | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | harvestcraft             | 1.12.2a      | Pam's HarvestCraft 1.12.2a.jar                | None                                     |

	Loaded coremods (and transformers):
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['WadeW78'/388, l='world', x=-219.34, y=75.00, z=226.13]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

Now I can't restart my server. It keeps crashing:

```
[20:49:28] [Server thread/INFO]: Loaded 483 advancements
[20:49:28] [Server thread/INFO]: Preparing start region for level 0
[20:49:34] [Server thread/INFO]: Preparing spawn area: 0%
[20:49:35] [Server thread/INFO]: Preparing spawn area: 4%
[20:49:36] [Server thread/INFO]: Preparing spawn area: 10%
[20:49:37] [Server thread/INFO]: Preparing spawn area: 18%
[20:49:38] [Server thread/INFO]: Preparing spawn area: 26%
[20:49:39] [Server thread/INFO]: Preparing spawn area: 36%
[20:49:40] [Server thread/INFO]: Preparing spawn area: 44%
[20:49:41] [Server thread/INFO]: Preparing spawn area: 52%
[20:49:42] [Server thread/INFO]: Preparing spawn area: 61%
[20:49:43] [Server thread/INFO]: Preparing spawn area: 74%
[20:49:44] [Server thread/INFO]: Preparing spawn area: 88%
[20:49:45] [Server thread/INFO]: Done (26.103s)! For help, type "help" or "?"
[20:49:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.tryStartNextResearch(TileResearchStation.java:245) ~[TileResearchStation.class:?]
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_73660_a(TileResearchStation.java:168) ~[TileResearchStation.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[20:49:47] [Server thread/ERROR]: This crash report has been saved to: /home/wadewegner/minecraft-1.12.2/./crash-reports/crash-2018-01-28_20.49.47-server.txt
[20:49:47] [Server thread/INFO]: Stopping server
[20:49:47] [Server thread/INFO]: Saving players
[20:49:47] [Server thread/INFO]: Saving worlds
[20:49:47] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[20:49:50] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[20:49:50] [Server thread/INFO]: Saving chunks for level 'world'/the_end
```

**Comment by wadewegner** [comment]
@P3pp3rF1y This isn't a good bug. Please let me know if you need more info or if you know a way I can get it restarted.

**Comment by darthvader45** [comment]
@P3pp3rF1y Seems the research table is trying to start research when there's no research selected, making it return null.  Might want to fix this.

**Comment by wadewegner** [comment]
@darthvader45 Anything I can do to fix this w/o requiring a fix in the mod?

Tried again. More debug info:
```
[23:33:05] [Server thread/INFO]: Done (22.614s)! For help, type "help" or "?"
[23:33:05] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: timeout value is negative
[23:33:05] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.sleep(Native Method)
[23:33:05] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[23:33:05] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[23:33:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.tryStartNextResearch(TileResearchStation.java:245) ~[TileResearchStation.class:?]
	at net.shadowmage.ancientwarfare.core.tile.TileResearchStation.func_73660_a(TileResearchStation.java:168) ~[TileResearchStation.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[23:33:07] [Server thread/ERROR]: This crash report has been saved to: /home/wadewegner/minecraft-1.12.2/./crash-reports/crash-2018-01-28_23.33.07-server.txt
[23:33:07] [Server thread/INFO]: Stopping server
[23:33:07] [Server thread/INFO]: Saving players
[23:33:07] [Server thread/INFO]: Saving worlds
[23:33:07] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[23:33:09] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[23:33:09] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[23:33:10] [Server thread/INFO] [FML]: Unloading dimension 0
[23:33:10] [Server thread/INFO] [FML]: Unloading dimension -1
[23:33:10] [Server thread/INFO] [FML]: Unloading dimension 1
[23:33:11] [Server thread/INFO] [FML]: Applying holder lookups
[23:33:11] [Server thread/INFO] [FML]: Holder lookups applied
[23:33:11] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[23:33:11] [Server Shutdown Thread/INFO]: Stopping server
[23:33:11] [Server Shutdown Thread/INFO]: Saving players
[23:33:11] [Server Shutdown Thread/INFO]: Saving worlds
```

**Comment by wadewegner** [comment]
Do either of you know a good tutorial for running debug builds? I'd be willing to try and debug this myself if I knew the steps. I've never built any mods before though.

**Comment by P3pp3rF1y** [comment]
So this issue was reported before in #573 and was fixed in the build I just released.

**Comment by wadewegner** [comment]
Ah, nice. Let me try that out.

Question: first time I'll try to update to a new release. Anything I should be aware of?

EDIT: @P3pp3rF1y, it looks like this affected my warehouse as all items in the warehouse are gone.

**Comment by wadewegner** [comment]
Also: where do I get the latest release? :)

**Comment by wadewegner** [comment]
Also: are you working on master or doing all of this on a branch? I'd like to consider jumping in and helping (if I can get it to build locally) but want to make sure I'm following your branch strategy.

**Comment by wadewegner** [comment]
I can confirm this fixed the issue. Thanks!

**Comment by darthvader45** [comment]
Yeah, that'll happen.  Hopefully you can mine and get the items back that way.
