### ISSUE TITLE
NpcAIPlayerOwnedGetFood causing server crash

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#586]
Another case of the server (this time a local game) continually crashing.

```
[16:01:56] [Server thread/INFO]: Preparing start region for level 0
[16:01:57] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at net.shadowmage.ancientwarfare.npc.ai.owned.NpcAIPlayerOwnedGetFood.tryUpkeep(NpcAIPlayerOwnedGetFood.java:71) ~[NpcAIPlayerOwnedGetFood.class:?]
	at net.shadowmage.ancientwarfare.npc.ai.owned.NpcAIPlayerOwnedGetFood.func_75246_d(NpcAIPlayerOwnedGetFood.java:56) ~[NpcAIPlayerOwnedGetFood.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
	at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.func_70636_d(NpcPlayerOwned.java:316) ~[NpcPlayerOwned.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:794) ~[NpcBase.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[16:01:57] [Server thread/ERROR]: This crash report has been saved to: C:\Users\wadew\AppData\Roaming\.minecraft\forge-1.12.2\crash-reports\crash-2018-01-28_16.01.57-server.txt
[16:01:57] [Server thread/INFO]: Stopping server
[16:01:57] [Server thread/INFO]: Saving players
[16:01:57] [Server thread/INFO]: Saving worlds
[16:01:57] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[16:01:58] [Server thread/INFO]: Saving chunks for level 'New World'/the_nether
[16:01:58] [Server thread/INFO]: Saving chunks for level 'New World'/the_end
```

Crash log:

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 1/28/18 4:01 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.shadowmage.ancientwarfare.npc.ai.owned.NpcAIPlayerOwnedGetFood.tryUpkeep(NpcAIPlayerOwnedGetFood.java:71)
	at net.shadowmage.ancientwarfare.npc.ai.owned.NpcAIPlayerOwnedGetFood.func_75246_d(NpcAIPlayerOwnedGetFood.java:56)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.func_70636_d(NpcPlayerOwned.java:316)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:794)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.npc.ai.owned.NpcAIPlayerOwnedGetFood.tryUpkeep(NpcAIPlayerOwnedGetFood.java:71)
	at net.shadowmage.ancientwarfare.npc.ai.owned.NpcAIPlayerOwnedGetFood.func_75246_d(NpcAIPlayerOwnedGetFood.java:56)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.func_70636_d(NpcPlayerOwned.java:316)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:794)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: ancientwarfarenpc:aw_npc_worker (net.shadowmage.ancientwarfare.npc.entity.NpcWorker)
	Entity ID: 102
	Entity Name: Craftsman
	Entity's Exact location: -1297.39, 4.00, 42.11
	Entity's Block location: World: (-1298,4,42), Chunk: (at 14,0,10 in -82,2; contains blocks -1312,0,32 to -1297,255,47), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Entity's Momentum: 0.12, -0.08, -0.03
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 7875482244179832091
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,2*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (-1281,4,26), Chunk: (at 15,0,10 in -81,1; contains blocks -1296,0,16 to -1281,255,31), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 8895 game time, 8895 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 59888 (now: false), thunder time: 64349 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 554255672 bytes (528 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2604 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version      | Source                                        | Signature                                |
	|:--------- |:------------------------ |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99    | forge-1.12.2-14.23.1.2604.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.1.2604 | forge-1.12.2-14.23.1.2604.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater        | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.1.5.331    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | ancientwarfareautomation | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@    | ancientwarfare-1.12.2-2.5.54.jar              | None                                     |
	| UCHIJAAAA | jei                      | 4.8.0.114    | jei_1.12.2-4.8.0.114.jar                      | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | harvestcraft             | 1.12.2a      | Pam's HarvestCraft 1.12.2a.jar                | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by P3pp3rF1y** [comment]
Can you retry with the latest release? I believe i have fixed this issue in there as well.

**Comment by wadewegner** [comment]
FWIW, we haven't seen this error in awhile and since updating. I'll close this and, if we see it it again, re-open. Thanks!
