### ISSUE TITLE
[bug report]Error when open the engineering station

### ISSUE THREAD

**Issue by huangzong1998** [P3pp3rF1y/AncientWarfare2#609]
sponge version: spongeforge-1.12.2-2611-7.1.0-BETA-2925
mod version: ancientwarfare-1.12.2-2.5.103

in server, when open the engineering station, it will error in console
`[13:12:01] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.spongepowered.common.item.inventory.lens.impl.slots.SlotLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.slots.CraftingOutputSlotLens
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2925]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: org.spongepowered.common.item.inventory.lens.impl.slots.SlotLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.slots.CraftingOutputSlotLens
        at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.<init>(CraftingInventoryLensImpl.java:55) ~[CraftingInventoryLensImpl.class:1.12.2-2611-7.1.0-BETA-2925]
        at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.<init>(CraftingInventoryLensImpl.java:49) ~[CraftingInventoryLensImpl.class:1.12.2-2611-7.1.0-BETA-2925]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:338) ~[ContainerUtil.class:1.12.2-2611-7.1.0-BETA-2925]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.getLens(ContainerUtil.java:233) ~[ContainerUtil.class:1.12.2-2611-7.1.0-BETA-2925]
        at net.minecraft.inventory.Container.spongeInit(Container.java:1013) ~[afr.class:?]
        at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1066) ~[afr.class:?]
        at net.minecraft.inventory.Container.func_75142_b(Container.java:1061) ~[afr.class:?]
        at net.minecraft.inventory.Container.func_75132_a(Container.java:1048) ~[afr.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:100) ~[FMLNetworkHandler.class:?]
        at net.shadowmage.ancientwarfare.core.network.NetworkHandler.openGui(NetworkHandler.java:192) ~[NetworkHandler.class:?]
        at net.shadowmage.ancientwarfare.core.network.NetworkHandler.openGui(NetworkHandler.java:184) ~[NetworkHandler.class:?]
        at net.shadowmage.ancientwarfare.core.block.BlockEngineeringStation.func_180639_a(BlockEngineeringStation.java:81) ~[BlockEngineeringStation.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1249) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zik000(NetHandlerPlayServer.java:2377) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) ~[PacketUtil.class:1.12.2-2611-7.1.0-BETA-2925]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
`

**Comment by huangzong1998** [comment]
And use warehouse crafting station will also have this problem.
i dont know if it is sponge's problem?

**Comment by P3pp3rF1y** [comment]
Based on the log it looks like sponge is having issues with itself so I would suggest to report to them. When I get to this I can retest in debug as well, but I suspect that I will just tell you a little more on what I am seeing sponge is trying to do there.

**Comment by huangzong1998** [comment]
thankyou very much. I think it can have an offical server, and many people will play it.

**Comment by P3pp3rF1y** [comment]
I have just uploaded new version on curseforge which should fix this crash.
