### ISSUE TITLE
Trade order GUI causing crash.

### ISSUE THREAD

**Issue by dnope** [P3pp3rF1y/AncientWarfare2#631]
Player crashes when they items to a new trade order on my server. Here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.11.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/2/18 12:58 AM
XRay version: 58
Description: Updating screen events

java.lang.IllegalArgumentException: Stack may not be null
	at net.shadowmage.ancientwarfare.core.inventory.ItemQuantityMap$ItemHashEntry.<init>(ItemQuantityMap.java:257)
	at net.shadowmage.ancientwarfare.core.inventory.ItemQuantityMap.addCount(ItemQuantityMap.java:84)
	at net.shadowmage.ancientwarfare.core.util.InventoryTools.compactStackList3(InventoryTools.java:572)
	at net.shadowmage.ancientwarfare.npc.trade.POTrade.updateCompactInput(POTrade.java:36)
	at net.shadowmage.ancientwarfare.npc.trade.POTrade.setInputStack(POTrade.java:20)
	at net.shadowmage.ancientwarfare.npc.gui.GuiTradeOrder$8.onSlotClicked(GuiTradeOrder.java:211)
	at net.shadowmage.ancientwarfare.core.gui.elements.ItemSlot$1.onEvent(ItemSlot.java:47)
	at net.shadowmage.ancientwarfare.core.gui.elements.GuiElement.handleMouseInput(GuiElement.java:97)
	at net.shadowmage.ancientwarfare.core.gui.elements.CompositeScrolled$1.onEvent(CompositeScrolled.java:87)
	at net.shadowmage.ancientwarfare.core.gui.elements.GuiElement.handleMouseInput(GuiElement.java:97)
	at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_146274_d(GuiContainerBase.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.shadowmage.ancientwarfare.core.inventory.ItemQuantityMap$ItemHashEntry.<init>(ItemQuantityMap.java:257)
	at net.shadowmage.ancientwarfare.core.inventory.ItemQuantityMap.addCount(ItemQuantityMap.java:84)
	at net.shadowmage.ancientwarfare.core.util.InventoryTools.compactStackList3(InventoryTools.java:572)
	at net.shadowmage.ancientwarfare.npc.trade.POTrade.updateCompactInput(POTrade.java:36)
	at net.shadowmage.ancientwarfare.npc.trade.POTrade.setInputStack(POTrade.java:20)
	at net.shadowmage.ancientwarfare.npc.gui.GuiTradeOrder$8.onSlotClicked(GuiTradeOrder.java:211)
	at net.shadowmage.ancientwarfare.core.gui.elements.ItemSlot$1.onEvent(ItemSlot.java:47)
	at net.shadowmage.ancientwarfare.core.gui.elements.GuiElement.handleMouseInput(GuiElement.java:97)
	at net.shadowmage.ancientwarfare.core.gui.elements.CompositeScrolled$1.onEvent(CompositeScrolled.java:87)
	at net.shadowmage.ancientwarfare.core.gui.elements.GuiElement.handleMouseInput(GuiElement.java:97)
	at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_146274_d(GuiContainerBase.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.shadowmage.ancientwarfare.npc.gui.GuiTradeOrder

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['D_NO'/1769, l='MpServer', x=-6.14, y=91.00, z=102.03], EntityOtherPlayerMP['CaliBurex_'/17031, l='MpServer', x=17.66, y=88.52, z=92.04]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-25,64,132), Chunk: (at 7,4,4 in -2,8; contains blocks -32,0,128 to -17,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 101395 game time, 12550 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 129 total; [EntityVillager['Villager'/1536, l='MpServer', x=9.05, y=88.00, z=40.50], MoCEntitySnake['Snake'/1538, l='MpServer', x=-14.87, y=88.00, z=34.13], EntitySlagmite['Slagmite'/1540, l='MpServer', x=-14.21, y=18.00, z=114.47], MoCEntityGoldFish['GoldFish'/1541, l='MpServer', x=-9.82, y=62.00, z=146.85], MoCEntityGoldFish['GoldFish'/1542, l='MpServer', x=-6.65, y=62.00, z=140.56], MoCEntityCrab['Crab'/1544, l='MpServer', x=-22.48, y=68.00, z=148.97], EntityVillager['Villager'/1550, l='MpServer', x=11.48, y=88.00, z=31.86], EntityVillager['Villager'/1551, l='MpServer', x=-10.52, y=88.00, z=34.57], EntityVillager['Villager'/1552, l='MpServer', x=9.70, y=88.00, z=40.50], EntityVillager['Villager'/1553, l='MpServer', x=9.89, y=88.00, z=30.38], EntityVillager['Villager'/1554, l='MpServer', x=15.68, y=87.94, z=51.52], EntityTreasureSlime['Treasure Slime'/16402, l='MpServer', x=55.49, y=20.00, z=105.49], EntityEnchantedBook['Bewitched Tome'/16405, l='MpServer', x=69.50, y=16.00, z=102.50], EntitySkeletonWarrior['Skeleton Warrior'/16413, l='MpServer', x=57.50, y=21.00, z=172.50], MoCEntityCrab['Crab'/1566, l='MpServer', x=11.94, y=68.00, z=162.50], EntitySlagmite['Slagmite'/1568, l='MpServer', x=25.80, y=23.00, z=24.80], MoCEntitySnake['Snake'/1569, l='MpServer', x=43.90, y=88.00, z=42.11], NpcPriest['Priest'/8744, l='MpServer', x=19.73, y=88.00, z=104.98], NpcWorker['Researcher'/1577, l='MpServer', x=22.84, y=88.00, z=101.46], NpcWorker['Researcher'/1578, l='MpServer', x=22.66, y=88.00, z=99.88], NpcCombat['Combat NPC'/1579, l='MpServer', x=22.00, y=88.00, z=98.00], NpcWorker['Farmer'/1580, l='MpServer', x=22.00, y=88.00, z=104.39], EntityTreasureSlime['Treasure Slime'/16941, l='MpServer', x=46.07, y=33.26, z=86.09], EntityGate['entity.aw_gate.name'/1582, l='MpServer', x=16.50, y=88.00, z=108.50], MoCEntityAnt['Ant'/1585, l='MpServer', x=28.50, y=67.00, z=163.53], MoCEntityPandaBear['PandaBear'/1587, l='MpServer', x=24.50, y=64.00, z=164.50], EntitySlagmite['Slagmite'/1588, l='MpServer', x=23.29, y=20.00, z=190.90], EntitySlagmite['Slagmite'/1590, l='MpServer', x=24.69, y=58.00, z=190.50], EntitySlagmite['Slagmite'/1593, l='MpServer', x=26.80, y=20.00, z=192.80], MoCEntityJellyFish['JellyFish'/1595, l='MpServer', x=47.72, y=61.00, z=158.13], MoCEntityAnchovy['Anchovy'/1597, l='MpServer', x=44.15, y=62.14, z=161.81], EntitySlagmite['Slagmite'/1600, l='MpServer', x=42.50, y=22.00, z=197.50], EntityHauntedTool['Haunted Tool'/16449, l='MpServer', x=0.50, y=72.00, z=178.75], MoCEntityMouse['Mouse'/1605, l='MpServer', x=57.50, y=53.00, z=54.50], EntitySlagmite['Slagmite'/1608, l='MpServer', x=60.50, y=45.00, z=95.50], MoCEntityElephant['Elephant'/1611, l='MpServer', x=58.76, y=92.00,

**Comment by P3pp3rF1y** [comment]
Again a case of outdated mod. I have changed this logic back in January, please get an up to date version.
