### ISSUE TITLE
Server crashes when players die near Ancient Warfare NPCs

### ISSUE THREAD

**Issue by dnope** [P3pp3rF1y/AncientWarfare2#632]
Here's the crash report for the server:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 18年4月2日 上午12:29
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70005_c_(NpcBase.java:727)
	at net.minecraft.entity.Entity.func_145748_c_(Entity.java:2741)
	at net.minecraft.util.CombatEntry.func_151522_h(SourceFile:57)
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:77)
	at net.minecraft.network.play.server.SPacketCombatEvent.<init>(SourceFile:48)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:476)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:369)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70005_c_(NpcBase.java:727)
	at net.minecraft.entity.Entity.func_145748_c_(Entity.java:2741)
	at net.minecraft.util.CombatEntry.func_151522_h(SourceFile:57)
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:77)
	at net.minecraft.network.play.server.SPacketCombatEvent.<init>(SourceFile:48)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:476)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:369)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.entity.projectile.EntityTippedArrow)
	Entity ID: 1840
	Entity Name: Arrow
	Entity's Exact location: 7.18, 89.95, 105.98
	Entity's Block location: World: (7,89,105), Chunk: (at 7,5,9 in 0,6; contains blocks 0,0,96 to 15,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -1.17, 0.18, 0.40
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['D_NO'/1758, l='world', x=6.13, y=89.00, z=106.29]]
	Chunk stats: ServerChunkCache: 626 Drop: 0
	Level seed: -2343044199635133650
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-25,64,132), Chunk: (at 7,4,4 in -2,8; contains blocks -32,0,128 to -17,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 67850 game time, 147866 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57214 (now: false), thunder time: 49476 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 646584640 bytes (616 MB) / 1038024704 bytes (989 MB) up to 1056243712 bytes (1007 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx1042M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version        | Source                                  | Signature                                |
	|:--------- |:------------------------ |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                      | 9.42           | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99      | forge-1.12.2-14.23.2.2611-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.2.2611   | forge-1.12.2-14.23.2.2611-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib           | 3.1.5.331      | CodeChickenLib-1.12.2.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | ancientwarfareautomation | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@      | Ancient-Warfare-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | extendedrenderer         | v1.0           | CoroUtil-1.12.1.jar                     | None                                     |
	| UCHIJAAAA | coroutil                 | 1.12.1-1.1.19  | CoroUtil-1.12.1.jar                     | None                                     |
	| UCHIJAAAA | configmod                | v1.0           | CoroUtil-1.12.1.jar                     | None                                     |
	| UCHIJAAAA | customspawner            | 3.11.4         | CustomMobSpawner-3.11.4.jar             | None                                     |
	| UCHIJAAAA | infernalmobs             | 1.7.3          | Infernal-Mobs-Mod-1.12.2.jar            | None                                     |
	| UCHIJAAAA | mercurius_updater        | 1.0            | MercuriusUpdater-1.12.2.jar             | None                                     |
	| UCHIJAAAA | mobends                  | 0.24           | Mo-Bends-Mod-1.12.jar                   | None                                     |
	| UCHIJAAAA | mocreatures              | 12.0.4         | Mo-Creatures-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | movillages               | 1.5.4          | Mo-Villages-Mod-1.12.2.jar              | None                                     |
	| UCHIJAAAA | mob_mash                 | 2.1            | Mob-Mash-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | primitivemobs            | 1.1.1          | Primitive-Mobs-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | roguelike                | 1.7.2          | Roguelike-Dungeons-Mod-1.12.2.jar       | None                                     |
	| UCHIJAAAA | spartanshields           | 1.3a           | Spartan-Shields-Mod-1.12.1.jar          | None                                     |
	| UCHIJAAAA | zombieawareness          | 1.12.1-1.11.10 | Zombie-Awareness-Mod-1.12.1.jar         | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 10; [EntityPlayerMP['D_NO'/1758, l='world', x=6.13, y=89.00, z=106.29]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by P3pp3rF1y** [comment]
So I am guessing you haven't downloaded ancient warfare from curseforge based on the file name. 
If so please understand that I only upload the mod to curseforge and I can't guarantee what other sites that reupload the mod would do with it (including malicious stuff like including malware).
I have also fixed this issue more than 3 months ago so they probably haven't reuploaded a new version.
