### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by Brigadon** [P3pp3rF1y/AncientWarfare2#639]
On load, the following crash log:
<spoiler>
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Core (ancientwarfare)
Caused by: java.lang.NullPointerException: Can't use a null-name for the registry, object net.shadowmage.ancientwarfare.core.crafting.ShapelessResearchRecipe$ShapelessWrapper@5e166930.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:275)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:108)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.addRecipe(AWCraftingManager.java:101)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.lambda$loadRecipes$4(AWCraftingManager.java:168)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager$$Lambda$373/1023021660.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.findFiles(AWCraftingManager.java:222)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.loadRecipes(AWCraftingManager.java:129)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.lambda$loadRecipes$2(AWCraftingManager.java:123)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager$$Lambda$374/2146963077.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.shadowmage.ancientwarfare.core.crafting.AWCraftingManager.loadRecipes(AWCraftingManager.java:123)
	at net.shadowmage.ancientwarfare.core.AncientWarfareCore.init(AncientWarfareCore.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1826134584 bytes (1741 MB) / 2575826944 bytes (2456 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2654 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                | Source                                          | Signature                                |
	|:----- |:------------------------ |:---------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                | 1.12.2                 | minecraft.jar                                   | None                                     |
	| UCHI  | mcp                      | 9.42                   | minecraft.jar                                   | None                                     |
	| UCHI  | FML                      | 8.0.99.99              | forge-1.12.2-14.23.2.2654.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                    | 14.23.2.2654           | forge-1.12.2-14.23.2.2654.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | uncraftingtable          | 1.8-beta6              | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
	| UCHI  | codechickenlib           | 3.1.6.339              | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHE  | ancientwarfare           | @VERSION@              | ancientwarfare-1.12.2-2.5.140.jar               | None                                     |
	| UCHI  | redstoneflux             | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHE  | ancientwarfareautomation | @VERSION@              | ancientwarfare-1.12.2-2.5.140.jar               | None                                     |
	| UCHE  | ancientwarfarenpc        | @VERSION@              | ancientwarfare-1.12.2-2.5.140.jar               | None                                     |
	| UCHE  | ancientwarfarestructure  | @VERSION@              | ancientwarfare-1.12.2-2.5.140.jar               | None                                     |
	| UCHE  | ancientwarfarevehicle    | @VERSION@              | ancientwarfare-1.12.2-2.5.140.jar               | None                                     |
	| UCHI  | jei                      | 4.8.5.159              | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCHI  | nucleus                  | 1.0                    | Nucleus-1.12.2-1.0-B15.jar                      | None                                     |
	| UCHI  | assistedprogression      | 2.0                    | AssistedProgression-1.12.2-2.0-B28.jar          | None                                     |
	| UCHI  | autopickup               | 2.5                    | AutoPickup-1.12-2.5.jar                         | None                                     |
	| UCHI  | betterbuilderswands      | 0.11.1                 | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHI  | birdsnests               | 2.1.0                  | BirdsNests1.12.2-2.1.0.jar                      | None                                     |
	| UCHI  | blockarmor               | 2.4.11                 | BlockArmor-1.12.2-2.4.11.jar                    | None                                     |
	| UCHI  | blockdrops               | 1.4.0                  | blockdrops-1.12.2-1.4.0.jar                     | None                                     |
	| UCHI  | chameleon                | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHI  | chesttransporter         | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCHI  | clarity                  | 1.1                    | clarity-1.1.jar                                 | None                                     |
	| UCHI  | clayworldgen             | 1.1.0-1.12             | ClayWorldGen-1.1.0-1.12.0.jar                   | None                                     |
	| UCHI  | craftablehorsearmour     | 1.3                    | CraftableHorseArmour-1.3.0-1.12.jar             | None                                     |
	| UCHI  | creeperconfetti          | 1.4.2                  | creeperconfetti-1.4.2.jar                       | None                                     |
	| UCHI  | cyclopscore              | 0.11.5                 | CyclopsCore-1.12.2-0.11.5.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHI  | elevatorid               | 1.3.6                  | ElevatorMod-1.12.2-1.3.6.jar                    | None                                     |
	| UCHI  | expandedbonemeal         | 1.2.1                  | expandedbonemeal-1.11-1.2.1.jar                 | None                                     |
	| UCHI  | fastleafdecay            | v14                    | FastLeafDecay-v14.jar                           | None                                     |
	| UCHI  | limelib                  | 1.7.10                 | limelib-1.12.2-1.7.10.jar                       | None                                     |
	| UCHI  | furnus                   | 2.1.5                  | furnus-1.12.2-2.1.5.jar                         | None                                     |
	| UCHI  | gravestone               | 1.10.1                 | gravestone-1.10.1.jar                           | None                                     |
	| UCHI  | harvest                  | 1.12-1.2.6-18          | Harvest-1.12-1.2.6-18.jar                       | None                                     |
	| UCHI  | waila                    | 1.8.25                 | Hwyla-1.8.25-B40_1.12.jar                       | None                                     |
	| UCHI  | jeiintegration           | 1.5.1.36               | jeiintegration_1.12.2-1.5.1.36.jar              | None                                     |
	| UCHI  | journeymap               | 1.12.2-5.5.2           | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHI  | jrftl                    | 1.1                    | JRFTL[1.12.2]-1.1.jar                           | None                                     |
	| UCHI  | lootbags                 | 2.5.4b                 | LootBags-1.12.2-2.5.4b.jar                      | None                                     |
	| UCHI  | mantle                   | 1.12-1.3.1.21          | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHI  | mcjtylib_ng              | 2.6.7                  | mcjtylib-1.12-2.6.7.jar                         | None                                     |
	| UCHI  | tconstruct               | 1.12.2-2.9.1.65        | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCHI  | moartinkers              | 0.5.4                  | moartinkers-0.5.4.jar                           | None                                     |
	| UCHI  | mob_grinding_utils       | 0.3.5                  | MobGrindingUtils-0.3.5.jar                      | None                                     |
	| UCHI  | noautojump               | 1.0                    | NoAutoJump-1.12-1.0.jar                         | None                                     |
	| UCHI  | recipehandler            | 0.10                   | NoMoreRecipeConflict-0.10(1.12.2).jar           | None                                     |
	| UCHI  | notenoughwands           | 1.6.1                  | notenoughwands-1.12-1.6.1.jar                   | None                                     |
	| UCHI  | omlib                    | 3.0.0-138              | omlib-1.12.2-3.0.0-138.jar                      | None                                     |
	| UCHI  | ompd                     | 3.0.0-35               | ompd-1.12.2-3.0.0-35.jar                        | None                                     |
	| UCHI  | openmodularturrets       | 3.0.0-236              | openmodularturrets-1.12.2-3.0.0-236.jar         | None                                     |
	| UCHI  | oreexcavation            | 1.4.113                | OreExcavation-1.4.113.jar                       | None                                     |
	| UCHI  | roguelike                | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHI  | storagedrawers           | 1.12-5.3.5             | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCHI  | tinker_io                | release 2.6.1          | tinker_io-1.12.2-release 2.6.1.jar              | None                                     |
	| UCHI  | tcomplement              | ${version}             | TinkersComplement-1.12.2-0.2.3b.jar             | None                                     |
	| UCHI  | tinkerskyblock           | 1.12-0.3.DEV.83d5fa9   | TinkerSkyblock-1.12-0.3.jar                     | None                                     |
	| UCHI  | tinkertoolleveling       | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UCHI  | tp                       | 3.2.20                 | tinyprogressions-1.12.2-3.3.24-Release.jar      | None                                     |
	| UCHI  | ts2k16                   | 1.2.8                  | TS2K16-1.2.8.jar                                | None                                     |
	| UCHI  | ultimate_unicorn_mod     | 1.5.14                 | ultimate_unicorn_mod-1.12.2-1.5.14.jar          | None                                     |
	| UCHI  | wailaharvestability      | 1.1.12                 | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHI  | waterstrainer            | 3.2.0                  | WaterStrainer-1.12-3.2.0.jar                    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
</spoiler>

**Comment by Brigadon** [comment]
It seems to be an artifact of the beta release... 140. 119 does not appear to have this issue.

**Comment by P3pp3rF1y** [comment]
Yeah, something I have missed in the implementation. Only happens when research system is turned off though, so turning it on will fix this.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on cf
