### ISSUE TITLE
Game Crash when steel was being crafted

### ISSUE THREAD

**Issue by JupiterYourHero** [P3pp3rF1y/AncientWarfare2#649]
at java.util.Arrays$ArrayList.get(Unknown Source)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at net.shadowmage.ancientwarfare.core.inventory.SlotResearchCrafting.func_190901_a(SlotResearchCrafting.java:108)
	at net.shadowmage.ancientwarfare.automation.container.ContainerCraftingRecipeMemory$1.func_190901_a(ContainerCraftingRecipeMemory.java:66)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_146274_d(GuiContainerBase.java:106)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. Looks like this is an issue with all shaped crafting recipes if the top left corner of the shape isn't in the first row and first column. For now you can craft it like that and I will get a fix in soon.
