### ISSUE TITLE
[1.12.2] [2.6.0.239] Crash when using JEI in Warehouse crafting station

### ISSUE THREAD

**Issue by wamc2017** [P3pp3rF1y/AncientWarfare2#706]
Hi,

I researched the warehouse  built it and added a crafting station to it. When the research book is in the right slot and I try to open the recipe for more storage blocks (for instance large warehouse block) in JEI the game crashes:

https://gist.github.com/wamc2017/c1e7666dd83176bbe4777ffc93838c6e

Mods used to test this issue (no other mods installed):
ancientwarfare-1.12.2-2.6.0.239
CodeChickenLib-1.12.2-3.1.8.341-universal
jei_1.12.2-4.9.2.196
forge-14.23.4.2707

Thanks for looking into it.

Best regards,
wamc

**Comment by P3pp3rF1y** [comment]
Just to be sure, this happens when you don't have any storage blocks added to the warehouse yet, right?

**Comment by wamc2017** [comment]
I added one storage block to the warehouse and the ingredients for the recipe are present in this storage block.

**Comment by P3pp3rF1y** [comment]
Could you add a screenshot of your setup? It's obvious I have to fix something but I have tested warehouse quite a few times and never had this happen, just never tested without any storage block in it. So I am guessing you may have an issue with your setup that doesn't recognize the warehouse or its storage block

**Comment by wamc2017** [comment]
Sure.

![2018-06-05_14 00 12](https://user-images.githubusercontent.com/33242447/40974877-4a816616-68c9-11e8-9d01-ab6bcffea0a0.png)

Edit: I also tried jei_1.12.2-4.9.1.188 (the version used in the gradle.properties) with the same result. Maybe I should also mention that the crash only happens if the book is inside the crafting station and the book got the proper research for the warehouse (trade).

**Comment by P3pp3rF1y** [comment]
alright so your issue is that crafting table goes on top of the controller as it checks for the existence of controller just below it, otherwise it doesn't know what to connect to. But I will also fix it so that it doesn't crash when used like this and maybe report a message to the user that it's not in correct position. And I will likely keep a note to allow this kind of usage in the future if I can make it so that it doesn't need to search for controller all the time.

**Comment by wamc2017** [comment]
Oh, ok, I thought it worked this way back in 1.7.10, also tried to put the workstation in the four cardinal directions of the warehouse block, never thought about to put it on the top... :smile:

Some indication what's wrong would be nice, because there isn't that much documentation around.

I'm closing this for now. Thanks. :)

**Comment by P3pp3rF1y** [comment]
Reopening to fix the crash and at least keep a note to enhance GUI To provide some guidance.

**Comment by AdaraChristine** [comment]
Is this related?
ancientwarfare-1.12.2-2.6.1.251
forge-1.12.2-14.23.3.2697

Description: Updating screen events

java.lang.NoClassDefFoundError: mezz/jei/config/SessionData at net.shadowmage.ancientwarfare.core.compat.jei.MultiRecipeTransferHandler.transferRecipe(MultiRecipeTransferHandler.java:80)
	at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:46)
	at mezz.jei.transfer.RecipeTransferUtil.getTransferRecipeError(RecipeTransferUtil.java:21)
	at mezz.jei.gui.recipes.RecipeTransferButton.init(RecipeTransferButton.java:28)
	at mezz.jei.gui.recipes.RecipesGui.addRecipeTransferButtons(RecipesGui.java:474)
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:451)
	at mezz.jei.gui.recipes.RecipesGui.func_73866_w_(RecipesGui.java:166)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at mezz.jei.gui.recipes.RecipesGui.open(RecipesGui.java:357)
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:377)
	at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:164)
	at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:117)
	at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:89)
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2132_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)

https://pastebin.com/ad6X1xx4
