### ISSUE TITLE
Was loading chunks and then it crashed.

### ISSUE THREAD

**Issue by BugmanBugman** [P3pp3rF1y/AncientWarfare2#740]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2018-07-17 23:04:13 CDT
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.structure.town.TownTemplateManager.getTemplatesValidAtPosition(TownTemplateManager.java:43)
    at net.shadowmage.ancientwarfare.structure.town.WorldTownGenerator.attemptGeneration(WorldTownGenerator.java:40)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.genTowns(WorldGenTickHandler.java:80)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:50)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1043_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

**Comment by P3pp3rF1y** [comment]
What version of AW are you using?

**Comment by BugmanBugman** [comment]
ancientwarfare-1.12.2-2.6.1.285.jar

**Comment by ProsperCraft** [comment]
Looks like I had the same problem - 
https://paste.fedoraproject.org/paste/6l5~nt9P5EO0xH-U1F0yXg
