### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by BannanaRepublic** [P3pp3rF1y/AncientWarfare2#751]
Time: 7/28/18 5:11 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.shadowmage.ancientwarfare.npc.registry.NpcDefaultsRegistry.getFactionNpcDefault(NpcDefaultsRegistry.java:36)
	at net.shadowmage.ancientwarfare.npc.entity.NpcLevelingStats.onBaseLevelGained(NpcLevelingStats.java:77)
	at net.shadowmage.ancientwarfare.npc.entity.NpcLevelingStats.addExperience(NpcLevelingStats.java:66)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.addExperience(NpcBase.java:669)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70074_a(NpcBase.java:616)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1172)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70652_k(NpcBase.java:240)
	at net.shadowmage.ancientwarfare.npc.ai.NpcAIAttackMeleeLongRange.doAttack(NpcAIAttackMeleeLongRange.java:27)
	at net.shadowmage.ancientwarfare.npc.ai.NpcAIAttack.func_75246_d(NpcAIAttack.java:51)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.npc.registry.NpcDefaultsRegistry.getFactionNpcDefault(NpcDefaultsRegistry.java:36)
	at net.shadowmage.ancientwarfare.npc.entity.NpcLevelingStats.onBaseLevelGained(NpcLevelingStats.java:77)
	at net.shadowmage.ancientwarfare.npc.entity.NpcLevelingStats.addExperience(NpcLevelingStats.java:66)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.addExperience(NpcBase.java:669)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70074_a(NpcBase.java:616)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1172)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70652_k(NpcBase.java:240)
	at net.shadowmage.ancientwarfare.npc.ai.NpcAIAttackMeleeLongRange.doAttack(NpcAIAttackMeleeLongRange.java:27)
	at net.shadowmage.ancientwarfare.npc.ai.NpcAIAttack.func_75246_d(NpcAIAttack.java:51)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: ancientwarfarenpc:faction.soldier (net.shadowmage.ancientwarfare.npc.entity.faction.NpcFactionSoldier)
	Entity ID: 8708
	Entity Name: Pirate Soldier
	Entity's Exact location: 2.39, 71.00, 383.57
	Entity's Block location: World: (2,71,383), Chunk: (at 2,4,15 in 0,23; contains blocks 0,0,368 to 15,255,383), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.01, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

**Comment by P3pp3rF1y** [comment]
Did this happen in a new world? 
Existing world where AW was updated from previous version?
Have you got custom structure templates that have faction npcs saved?
Or perhaps even changed factions?

**Comment by BannanaRepublic** [comment]
Brand new world, the only custom things I have added are I am using some BDcraft skins, but I have always used those with your mod.

**Comment by P3pp3rF1y** [comment]
I tried recreating this, but I am unable to despite many npcs I have leveled up, so I am going to close. Feel free to open new issue if this happens again.

**Comment by BannanaRepublic** [comment]
I think there was some kind of compat problem with some other mod that got updated I see no more ticking entity errors.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
