### ISSUE TITLE
1.7.10 Skin Crash

### ISSUE THREAD

**Issue by nsirii** [P3pp3rF1y/AncientWarfare2#757]
So I've created a world with a bunch of medieval-themed mods and Ancient Warfare is probably one of the most important mods so I really want and need it to work, as I am thinking of starting a roleplay type of series. My problem is with the skin customization of the NPCs; I followed every instruction of this tutorial on youtube and put the file into the skins folder which is found in the config folder, but the game crashes before it even starts up?

**Comment by nsirii** [comment]
Crash Report:

Description: Registering texture

java.lang.NullPointerException: Registering texture
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110987_a(TextureUtil.java:44)
	at net.shadowmage.ancientwarfare.core.util.TextureImageBased.func_110551_a(TextureImageBased.java:21)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkinPackImage(NpcClientProxy.java:84)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinPackImage(NpcSkinManager.java:189)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadPackFromZip(NpcSkinManager.java:91)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.parseZipFiles(NpcSkinManager.java:141)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinPacks(NpcSkinManager.java:57)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkins(NpcClientProxy.java:76)
	at net.shadowmage.ancientwarfare.npc.AncientWarfareNPC.postInit(AncientWarfareNPC.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110987_a(TextureUtil.java:44)
	at net.shadowmage.ancientwarfare.core.util.TextureImageBased.func_110551_a(TextureImageBased.java:21)

-- Resource location being registered --
Details:
	Resource location: ancientwarfare:skinpack/Archive.zip/__MACOSX/._combat.png
	Texture object class: net.shadowmage.ancientwarfare.core.util.TextureImageBased
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkinPackImage(NpcClientProxy.java:84)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinPackImage(NpcSkinManager.java:189)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadPackFromZip(NpcSkinManager.java:91)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.parseZipFiles(NpcSkinManager.java:141)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinPacks(NpcSkinManager.java:57)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkins(NpcClientProxy.java:76)
	at net.shadowmage.ancientwarfare.npc.AncientWarfareNPC.postInit(AncientWarfareNPC.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.13.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 691715656 bytes (659 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_E7 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJ	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJ	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJ	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJ	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJ	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJ	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJ	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHI	bettervillages{0.4} [Better Villages Mod] (Better-Villages-Mod-1.7.10.jar) 
	UCHI	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft[v1.11.6][MC1.7.10].jar) 
	UCHI	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.1+-+MC+1.7.10.jar) 
	UCHI	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry-Mod-1.7.10.jar) 
	UCHI	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner+3.3.0.zip) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHI	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4_1.7.10.jar) 
	UCHI	props{2.4} [Decocraft] (Decocraft-2.4_1.7.10.jar) 
	UCHI	doggytalents{1.14.2.317} [Doggy Talents] (DoggyTalents-1.7.10-1.14.2.317-universal.jar) 
	UCHI	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHI	exoticbirds{1.0} [Exotic Birds] (Exotic+Birds+1.7.10-1.4.6.jar) 
	UCHI	ExtrabiomesXL{3.16.4} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.4.jar) 
	UCHI	harvestcraft{1.7.10j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) 
	UCHI	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHI	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHI	naturescompass{1.3.0} [Nature's Compass] (Natures-Compass-Mod-1.7.10 (1).jar) 
	UCHI	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pams-Weee-Flowers-Mod-1.7.10.zip) 
	UCHI	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHI	SC0_SpaceCore{0.7.14} [SpaceCore] (SpaceCore-1.7.10.jar) 
	UCHI	SC0_Wings{1.2.6} [Survival Wings] (Survival-Wings-Mod-1.7.10.jar) 
	UCHI	taleofkingdoms{1.0.12.4} [Tale of Kingdoms] (Tale+of+Kingdoms+1.7.10+-+B12.5.2.jar) 
	UCHI	thirstmod{1.8.9} [Thirst Mod] (thirstmod-1.8.9.jar) 
	UCHI	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHI	XaeroMinimap{1.13.9} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.32.48' Renderer: 'Intel(R) HD Graphics 6000'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-10.32.48, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Skyrim_soundpack_v4.2 (not final verison).zip, JSTR_Modded_Universal (1).zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.32.48
	OpenGlRenderer: Intel(R) HD Graphics 6000
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by P3pp3rF1y** [comment]
Sorry, I don't support 1.7.10 anymore, but from the quick look at the exception log above it seems like there may be issue with special characters used for image files so I would try to remove those.
