### ISSUE TITLE
Crash when a bandit soldier is killed by max level Doggy Talents wolf.

### ISSUE THREAD

**Issue by Neglevin** [P3pp3rF1y/AncientWarfare2#758]
The bandit's model also stays where it was despite being already dead when I logged back into the world. Here's the crash: https://pastebin.com/jMCg0pY0

**Comment by AdaraChristine** [comment]
Same issue with Sophisticated wolves
8/7/18 5:46 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.shadowmage.ancientwarfare.npc.ai.NpcAI.isAlwaysHostileToNpcs(NpcAI.java:168)
	at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.isHostileTowards(NpcFaction.java:82)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70693_a(NpcBase.java:912)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:383)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70030_z(NpcBase.java:339)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

**Comment by m1cr0man** [comment]
Was experiencing the same issue on my server. I don't have Doggy Talents but I do have Sophisticated Wolves. I updated to the 309 unstable release and it doesn't seem to be crashing any more.

Thanks for a quick turnaround on that fix :)
