### ISSUE TITLE
Crash on start (Library update?)

### ISSUE THREAD

**Issue by m1cr0man** [P3pp3rF1y/AncientWarfare2#768]
As of today Ancient Warfare has started crashing on startup. I've tested against version 309 unstable and 317 unstable.

I haven't changed a thing on my mod pack but I suspect that MultiMC may have updated the game libraries and this has somehow caused the crash? It is occurring on 3 totally different computers/clients despite having worked fine for the past week or so.

Here's the error:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Core (ancientwarfare)
Caused by: java.lang.NullPointerException
	at net.shadowmage.ancientwarfare.core.manual.ManualContentRegistry$ManualContentParser.parse(ManualContentRegistry.java:50)
	at net.shadowmage.ancientwarfare.core.registry.RegistryLoader.loadFile(RegistryLoader.java:143)
	at net.shadowmage.ancientwarfare.core.registry.RegistryLoader.loadRegistries(RegistryLoader.java:105)
	at net.shadowmage.ancientwarfare.core.registry.RegistryLoader.loadRegistries(RegistryLoader.java:80)
	at net.shadowmage.ancientwarfare.core.registry.RegistryLoader.load(RegistryLoader.java:62)
	at net.shadowmage.ancientwarfare.core.registry.RegistryLoader.load(RegistryLoader.java:44)
	at net.shadowmage.ancientwarfare.core.AncientWarfareCore.init(AncientWarfareCore.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
[Full log](https://paste.ee/p/Hx8Gu)

I tried resetting my configs and such but to no avail.

I'm working on getting a diff of my libraries too.

**Comment by wamc2017** [comment]
Try updating forge to 14.23.4.2751 or newer.

**Comment by P3pp3rF1y** [comment]
or just restart now, apparently this was fixed on Mojang side so should work even without update

**Comment by m1cr0man** [comment]
Hm doesn't seem to be working yet anyway...Upgrading forge fixed it immediately although I'd prefer if I could stick with the version I'm on otherwise I have to update my server and redistribute my mod pack. I'll see what happens in a few hours.

Thanks for the quick responses :)

**Comment by P3pp3rF1y** [comment]
Closing this, here's the related PR to fix the issue on forge side in case you want to comment on whether the Mojang fix is working later on https://github.com/MinecraftForge/MinecraftForge/pull/5105
