### ISSUE TITLE
CRASH after NPC KILLED by TAMED WOLF

### ISSUE THREAD

**Issue by dldummy** [P3pp3rF1y/AncientWarfare2#783]
Reproducable CRASH if NPC enemy is killed by a tamed wolf.
Not in case of untamed wolf if they get in the line of fire. (they get angry but have nos dest to attack)

Tested with :
MC 1.12.2
forge 1.12.2-14.23.4.2757
ancientwarfare-1.12.2-2.6.1.298
CodeChickenLib-1.12.2-3.2.1.350-universal
nothing else ....

Crash REPORT:
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.shadowmage.ancientwarfare.npc.ai.NpcAI.isAlwaysHostileToNpcs(NpcAI.java:168)
	at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.isHostileTowards(NpcFaction.java:82)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70693_a(NpcBase.java:912)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:385)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:324)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70030_z(NpcBase.java:339)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2089)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.npc.ai.NpcAI.isAlwaysHostileToNpcs(NpcAI.java:168)
	at net.shadowmage.ancientwarfare.npc.entity.faction.NpcFaction.isHostileTowards(NpcFaction.java:82)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70693_a(NpcBase.java:912)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:385)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:324)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70030_z(NpcBase.java:339)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2089)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:820)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: ancientwarfarenpc:faction.archer (net.shadowmage.ancientwarfare.npc.entity.faction.NpcFactionArcher)
	Entity ID: 9925
	Entity Name: Pirate Archer
	Entity's Exact location: 840.30, 8.50, -788.26
	Entity's Block location: World: (840,8,-789), Chunk: (at 8,0,11 in 52,-50; contains blocks 832,0,-800 to 847,255,-785), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['TheBiggestNoob'/708, l='New World', x=843.47, y=4.00, z=-904.18]]
	Chunk stats: ServerChunkCache: 630 Drop: 0
	Level seed: 1663303020015385921
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,2*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (846,4,-930), Chunk: (at 14,0,14 in 52,-59; contains blocks 832,0,-944 to 847,255,-929), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 6920 game time, 6920 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 162525 (now: false), thunder time: 171380 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 52958288 bytes (50 MB) / 735576064 bytes (701 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2757 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version          | Source                                        | Signature                                |
	|:--------- |:------------------------ |:---------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42             | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99        | forge-1.12.2-14.23.4.2757-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.4.2757     | forge-1.12.2-14.23.4.2757-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib           | 3.2.1.350        | CodeChickenLib-1.12.2-3.2.1.350-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | 1.12.2-2.6.1.298 | ancientwarfare-1.12.2-2.6.1.298.jar           | None                                     |
	| UCHIJAAAA | ancientwarfareautomation | 1.12.2-2.6.1.298 | ancientwarfare-1.12.2-2.6.1.298.jar           | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | 1.12.2-2.6.1.298 | ancientwarfare-1.12.2-2.6.1.298.jar           | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | 1.12.2-2.6.1.298 | ancientwarfare-1.12.2-2.6.1.298.jar           | None                                     |
	| UCHIJAAAA | ancientwarfarevehicle    | 1.12.2-2.6.1.298 | ancientwarfare-1.12.2-2.6.1.298.jar           | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TheBiggestNoob'/708, l='New World', x=843.47, y=4.00, z=-904.18]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by P3pp3rF1y** [comment]
Please update to the latest version of AW available on Curseforge where this is fixed.

**Comment by dldummy** [comment]
Sorry .. i was sure im using the newest one ..
