### ISSUE TITLE
Torque system NPE

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#79]
[11:45:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueTransportConduit.getConnectionsInt(TileTorqueTransportConduit.java:55) ~[TileTorqueTransportConduit.class:?]
    at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueTransportConduit.func_145844_m(TileTorqueTransportConduit.java:99) ~[TileTorqueTransportConduit.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540) ~[mw.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276) ~[mw.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2043) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2007) ~[ahb.class:?]
    at WorldServerOF.func_72870_g(WorldServerOF.java:394) ~[WorldServerOF.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1860) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
    ... 4 more

On loading a world that has existing torque system in place. No prior issues. Do you need the full log?

**Comment by Dulciphi** [comment]
Log of the same crash trying to load the same world with a very reduced mods list (to clear clutter from the log and eliminate other mods as the issue).
http://paste.ee/p/rpWJP - using Forge version 1208

Log of the same instance, loading the same world, using no additional mods because this time I'm loading it with the recommended Forge version 1180. It loads. 
http://paste.ee/p/tOH7S

**Comment by shadowmage45** [comment]
Thanks for the report.

This is due to some questionable changes that Forge made to the way neighbor updates/tile-entities work in one of the recent Forge releases.

Nothing I can do about it at the moment -- they pretty effectively broke the block neighbor-changed/TE-neighbor update code path.  I'm going to have to rework the entire update system to accomodate their changes, and even then it might not be possible (which in the end will mean the system will function like @#%^ as it will be constantly looking up neighbors instead of caching them).

Thanks Forge!  Love it when they give me extra shit to fix because they want to freaking break everything.

**Comment by shadowmage45** [comment]
As stated, this -should- fix the crash issues, hopefully with little/no performance hit.  

However, will need to thoroughly test the torque conduits to make sure the forge changes didn't fubar any other code paths.

Not sure why forge decided that changing vanilla functionality was a good idea (...its not...), but hopefully this problem will not pop up again.
