### ISSUE TITLE
Crash on startup [version 2.6.1.390]

### ISSUE THREAD

**Issue by teagan75** [P3pp3rF1y/AncientWarfare2#838]
https://pastebin.com/FPbwAxZs

**Comment by teagan75** [comment]
nvm. I guess unlike the 1.7.10 version, I have to allow structures to spawn or it crashes. Before that was controlled by the mod and not with initial creation of a world.

**Comment by P3pp3rF1y** [comment]
You can of course disable structure spawning. That crash you got was because a class was missing that is in the mod for sure so I have no idea what happened there. 
Does it really happen by simply disabling structure gen? That part of code actually isn’t even dependent on that config value and gets called every time.

**Comment by teagan75** [comment]
I only get the crash when disabling structure gen when creating a world. When it’s enabled it doesn’t crash. I thought it was strange too.

**Comment by P3pp3rF1y** [comment]
You mean the option that you select in mc screen when creating world?
Based on that crash log the crash happened during mc loading so well before you would be able to get to that screen. Was there perhaps a different crash?

**Comment by P3pp3rF1y** [comment]
Reopening as it seems like there’s an issue in some case

**Comment by teagan75** [comment]
It crashes only when Ancient Warfare is enabled and disabling structure gen via the mc screen before creating a world. Not if I disable AW Structures in the config. 

For comparison (but it really is a simple fix) I.7.10 I could disable structure gen via the mc screen and AW Structures would still spawn.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this and that crash log really points to an issue during the loading of the game. if you are able to recreate, please let me know any additional steps I need to go through.

**Comment by CyberCelestial** [comment]
I believe I am having the same error with the same version.

https://pastebin.com/9u5M7FFZ

I am of course using the latest versions of Ancient Warfare and its dependency, as well as the latest Forge. I tried a couple different versions of forge as well, just to check.

**Comment by P3pp3rF1y** [comment]
When does this happen for you? During the game load or world load?

**Comment by P3pp3rF1y** [comment]
Just to be extra sure, you have downloaded the mod from curseforge, right?
Asking because this is a very odd crash where it's missing class that is definitely there in the released file as well as if it was missing it would be crashing for everyone and there would be more reports of it. 

And actually one more, does it happen for you with just Ancient Warfare? There may be a potential of another mod messing with AW.

**Comment by teagan75** [comment]
I dl from Curse. The crash happens with world load.

**Comment by CyberCelestial** [comment]
Game load, yes from curseforge, and I haven't tried isolating AW yet; this happened during a separate testing run I'm doing that's not yet finished.

**Comment by Jackiecrazy** [comment]
Same latest version, crashed on startup as well. When I poke around the source with JD-GUI (sorry), I note that SoundHelper gives an internal error while other classes decompile fine.

**Comment by P3pp3rF1y** [comment]
We have solved this issue for several people by having them update forge. Forge that ends with 2765 or later works.

**Comment by TheRandomGuy2** [comment]
i have forge 2768, and when it crashes, it happens when its loading code chicken lib, i have the mod and the core mod, and a map mod

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 12/3/18 5:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 966690992 bytes (921 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version      | Source                           | Signature                                |
	|:----- |:------------------------ |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                | 1.12.2       | minecraft.jar                    | None                                     |
	| UCH   | mcp                      | 9.42         | minecraft.jar                    | None                                     |
	| UCH   | FML                      | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                    | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCEE  | codechickenlib           | 3.2.2.353    | CodeChickenLib-1.12.2.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | ancientwarfare           | @VERSION@    | ancientwarfare-1.12.2-2.4.30.jar | None                                     |
	| UC    | ancientwarfareautomation | @VERSION@    | ancientwarfare-1.12.2-2.4.30.jar | None                                     |
	| UC    | ancientwarfarenpc        | @VERSION@    | ancientwarfare-1.12.2-2.4.30.jar | None                                     |
	| UC    | ancientwarfarestructure  | @VERSION@    | ancientwarfare-1.12.2-2.4.30.jar | None                                     |
	| UC    | journeymap               | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GT 730/PCIe/SSE2'****

**Comment by TheRandomGuy2** [comment]
Update: i got the mod the work by deleating the config for ccl and aw, it might be bacause the config picks up options for ccl and this causes the game to crash, i will test it now

**Comment by TheRandomGuy2** [comment]
I have been testing and this is what it might be, i found chocolate quest mod for 1.7.10, in the same ccl config with aw and other 1.12.2 mod, it could be a bug with configs for different versions that crash the game, it could also be a mod for 1.12.2 that was causing it to crash, i have not tested all of them, i did found out that nei with aw will crash but jei and aw will not, it could be tested more but i am done for now
