### ISSUE TITLE
lan disconnect on newest version .497

### ISSUE THREAD

**Issue by njtxus** [P3pp3rF1y/AncientWarfare2#869]
no players can connect when using  .497 version. always comes up with "forcibly disconnected" error. earlier versions work fine.

**Comment by P3pp3rF1y** [comment]
could you add more info from what you can see in your logs? we definitely have players playing with the latest version on servers so it's not just the update to latest that caused it, must be something specific about what kind of blocks/items you have used on your server.

**Comment by njtxus** [comment]
i think this is the relevant data.  it client connects to me and then almost immediately throws
this. there is no real crash just cant connect unless we use the previous version. i also attached the complete log if that helps. thanks for your time

[2018-12-25-2.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/2711184/2018-12-25-2.log)
 

[20:21:05] [Netty Client IO #0/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_191]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by P3pp3rF1y** [comment]
That client log doesnt have any helpful data in it. Could you add the server log from the time when you try to connect?

**Comment by njtxus** [comment]
[latest.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/2713102/latest.log)

i think this is right.

**Comment by njtxus** [comment]
i tried to use the newest version just byitself with no other mods and the lan worked! it seems to be an incompatibility with another mod. maybe because of the new structures based on other mods?

**Comment by njtxus** [comment]
tried removing multiple mods and nothing seems to work with the newest version in multiplayer. thanks for your trouble though! ill just stick with the old version for now.

**Comment by AdaraChristine** [comment]
Im having the same problem and ive isolated where its coming from. 
 MY error---Could not locate biome: minecraft_beach while registering template: EmpireHamlet1 for world generation.
Your error---Could not locate biome: biomesoplenty:dead_forest while registering template: BrigandCampPlainsSmall for world generation.
I was able to load a world after setting the default structure pack to false
We both have biome mods installed
@P3pp3rF1y

**Comment by P3pp3rF1y** [comment]
I am guessing this is caused by the synchronization of structures from server to client when the player joins. The reason being there's now a lot of them and thus the synchronization may timeout the connection on slower internet connections. I will see what I can do about making it not synchronize on connect but rather when the individual structure is used in some way on client.

**Comment by AdaraChristine** [comment]
Appears fixed, thanks for all your work

**Comment by njtxus** [comment]
it's fixed thanks a lot!

**Comment by P3pp3rF1y** [comment]
You’re welcome
