### ISSUE TITLE
Crash with the 668 build.

### ISSUE THREAD

**Issue by ArkenorOakshadow** [P3pp3rF1y/AncientWarfare2#945]
A couple of minutes into a new world, I got this crash. I had been running the previous version with no issues.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.shadowmage.ancientwarfare.core.network.NetworkHandler.sendToAllPlayers(NetworkHandler.java:158)
    at net.shadowmage.ancientwarfare.structure.gamedata.StructureMap.setGeneratedAt(StructureMap.java:74)
    at net.shadowmage.ancientwarfare.structure.network.PacketStructureEntry.execute(PacketStructureEntry.java:60)
    at net.shadowmage.ancientwarfare.core.network.PacketBase.execute(PacketBase.java:50)
    at net.shadowmage.ancientwarfare.core.network.PacketHandlerServer.lambda$onClientPacket$1(PacketHandlerServer.java:29)
    at net.shadowmage.ancientwarfare.core.network.PacketHandlerServer$$Lambda$5133/911110827.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more
```

https://paste.dimdev.org/pukepohivo.mccrash

**Comment by WinDanesz** [comment]
Please update to Forge 14.23.5.2815+ meanwhile it's being added to dependencies, to fix the crash.

**Comment by ArkenorOakshadow** [comment]
I'm already using 14.23.5.2836

**Comment by ArkenorOakshadow** [comment]
Is this the same issue that was addressed here: https://github.com/P3pp3rF1y/AncientWarfare2/issues/951 ?

**Comment by P3pp3rF1y** [comment]
@ArkenorOakshadow no this is a different issue and honestly I really have no idea why this is happening for you as that basically means that at that point there's no server instance running but then you wouldn't be able to play on the server if it keeps happening I would need you to try to figure out what mod in your modpack is causing this, it's likely one of the core mods.

**Comment by ArkenorOakshadow** [comment]
It's only happening in multiplayer. Everything behaves fine in singleplayer. I think ThatPolishKid99 is going to run some tests with a server.

It does seem to be identical to the crashlog posted in a comment here, so it is not just me: https://github.com/P3pp3rF1y/AncientWarfare2/issues/951#issuecomment-494646182

**Comment by ThatPolishKid99** [comment]
I did run what can essentially amount to a test yesterday, in the form of just regular gameplay on server. I experienced no such crashes. I’d recommend narrowing down which mods are causing the crash.

**Comment by ArkenorOakshadow** [comment]
Regarding the fix here: https://github.com/P3pp3rF1y/AncientWarfare2/commit/133a4ccf9bc0f8e76079ef20870dd483b0818011

Are references to EntityPlayerSP always bad for code running on a server under later versions of Forge?

Because going through the source code, it's also used in BlockChair.java and BlockTable.java.

Probably doesn't help me at all, but I'm at the flailing around stage.

**Comment by ArkenorOakshadow** [comment]
OK, I have further knowledge. I've been ripping out my coremods one at a time.

Even without Vanillafix, which gives you a crash popup, the crash is not fatal. In fact you never know about it. Unless you look at your logs. This would explain the lack of reports, as you need to be playing on a server, have a recent Forge AND use Vanillafix to know it happened. Unfortunately I need Vanillafix for some of its other benefits, and in any case, we should try to get to the bottom of this.

It occurs to me that if ThatPolishKid99's tests did not include Vanillafix, the issue may have been missed.

What I can tell you is that it happens when loading Ancient Warfare structures onto the edge of the map. They're quite rare in my setup, so it's easy for me to figure out that that's what's happening.

**Comment by WinDanesz** [comment]
So it only happened when you were generating AW structures near the world boundaries?
Did you encounter this bug with unlimited world sizes?

**Comment by ArkenorOakshadow** [comment]
When I say the edge of the map, I mean on the edge of the visible map. That is to say, when my client receives the information about them for the first time, or thereabouts. It can be one crash report, or a whole pile of them. Varies.

Given that it appears that it's not a terribly devastating crash I might just put up with the crash report popups. Hopefully it's not quietly having an awful effect on something. It doesn't seem to be being caused by any of my coremods.

It couldn't possibly be due to EntityPlayerSP being referenced by BlockChair.java and BlockTable.java could it? I posted about that earlier, then deleted it in a crisis of confidence, but now I wonder.

I'm guessing those were for these 668-build additions: Added stools that player can sit on for all vanilla wood variants. (model by WinDanesz)
Added simple wood tables in all wood variants, also form multiblock when multi placed next to each other (model by WinDanesz)

Are they used in your structures?

**Comment by ArkenorOakshadow** [comment]
So, I thought it would be a good idea to figure out which version of Forge this crash begins at. I went back a few at a time. I eventually reached 2815, and the crash still occurs. A valuable reminder for me to always question premises. 

So anyway, probably not Forge version related. The good news is that 2836 and 2838 don't seem to have any additional problems.
