### ISSUE TITLE
when trying to set routing order

### ISSUE THREAD

**Issue by lcswolf** [P3pp3rF1y/AncientWarfare2#951]
[11:49:37] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.shadowmage.ancientwarfare.npc.item.ItemRoutingOrder.onKeyAction(ItemRoutingOrder.java:47) ~[ItemRoutingOrder.class:?]
	at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.executeKeyPress(PacketItemInteraction.java:48) ~[PacketItemInteraction.class:?]
	at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.execute(PacketItemInteraction.java:36) ~[PacketItemInteraction.class:?]
	at net.shadowmage.ancientwarfare.core.network.PacketHandlerServer.lambda$onServerPacket$0(PacketHandlerServer.java:21) ~[PacketHandlerServer.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at net.shadowmage.ancientwarfare.npc.item.ItemRoutingOrder.onKeyAction(ItemRoutingOrder.java:47) ~[ItemRoutingOrder.class:?]
	at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.executeKeyPress(PacketItemInteraction.java:48) ~[PacketItemInteraction.class:?]
	at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.execute(PacketItemInteraction.java:36) ~[PacketItemInteraction.class:?]
	at net.shadowmage.ancientwarfare.core.network.PacketHandlerServer.lambda$onServerPacket$0(PacketHandlerServer.java:21) ~[PacketHandlerServer.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by WinDanesz** [comment]
Is this on a server?
If so, you have the exact same AW version in both client and server side?

**Comment by lcswolf** [comment]
yes on a server and same version

**Comment by ThatPolishKid99** [comment]
Hi, can we get the full crash report? Is this an old world you loaded up into the new version? If so, is it an old routing order from before the new version?

**Comment by talhanation** [comment]
I have the same problem with the latest version of  ancientwarfare-1.12.2-2.7.0.668 and forge 1.12.2_14.23.5.2836

**Comment by talhanation** [comment]
btw its not a crash this item just dont work in Multiplayer, here is my error log :

**Comment by talhanation** [comment]
[01:07:38] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
        at net.shadowmage.ancientwarfare.npc.item.ItemRoutingOrder.onKeyAction(ItemRoutingOrder.java:47) ~[ItemRoutingOrder.class:?]
        at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.executeKeyPress(PacketItemInteraction.java:48) ~[PacketItemInteraction.class:?]
        at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.execute(PacketItemInteraction.java:36) ~[PacketItemInteraction.class:?]
        at net.shadowmage.ancientwarfare.core.network.PacketHandlerServer.lambda$onServerPacket$0(PacketHandlerServer.java:21) ~[PacketHandlerServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at net.shadowmage.ancientwarfare.npc.item.ItemRoutingOrder.onKeyAction(ItemRoutingOrder.java:47) ~[ItemRoutingOrder.class:?]
        at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.executeKeyPress(PacketItemInteraction.java:48) ~[PacketItemInteraction.class:?]
        at net.shadowmage.ancientwarfare.core.network.PacketItemInteraction.execute(PacketItemInteraction.java:36) ~[PacketItemInteraction.class:?]
        at net.shadowmage.ancientwarfare.core.network.PacketHandlerServer.lambda$onServerPacket$0(PacketHandlerServer.java:21) ~[PacketHandlerServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by ckhomo** [comment]
[crash-2019-05-22_12.10.00-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3205574/crash-2019-05-22_12.10.00-client.txt)

Guess it is the same problem as the topic
On a server, both client and server are 668 build
forge-1.12.2-14.23.5.2836-universal
