### ISSUE TITLE
Selecting an NPC with a command baton on a dedicated server does nothing

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#957]
When trying to select an NPC with the command staff nothing happens aside from this error being posted in the server log

```        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
        at net.shadowmage.ancientwarfare.npc.item.ItemCommandBaton.func_77659_a(ItemCommandBaton.java:149) ~[ItemCommandBaton.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at net.shadowmage.ancientwarfare.npc.item.ItemCommandBaton.func_77659_a(ItemCommandBaton.java:149) ~[ItemCommandBaton.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more```

**Comment by ArkenorOakshadow** [comment]
This appears to be the same issue addressed here: https://github.com/P3pp3rF1y/AncientWarfare2/issues/951

**Comment by ThatPolishKid99** [comment]
Fixed in the latest version of the mod.
